/** Built-in file discovery rules. These are product behavior, not settings. */
export const FILE_HANDLING_RULES = {
  included: {
    mediaExtensions: [
      '.png',
      '.pdf',
      '.jpeg',
      '.jpg',
      '.gif',
      '.heic',
      '.heif',
      '.webp',
      '.wav',
      '.m4a',
      '.mp3',
      '.aiff',
      '.aac',
      '.opus',
      '.l16',
      '.alaw',
      '.mulaw',
      '.ogg',
      '.flac',
    ],
    inputExtensions: ['.txt', '.tex', '.md'],
    contextExtensions: ['.txt', '.tex', '.md', '.bib', '.bbl', '.cls', '.sty'],
    editedExtensions: ['.txt', '.tex'],
  },
  ignored: {
    fileExtensions: [
      '.pdf',
      '.bst',
      '.json',
      '.py',
      '.ipynb',
      '.png',
      '.vsix',
      '.ts',
      '.js',
      '.yaml',
    ],
    inputFiles: ['command.tex', 'commands.tex', 'preamble.tex', 'yaml'],
    inputDirectories: [],
    mediaDirectories: [
      'build',
      'node_modules',
      '__pycache__',
      'versions',
      'history',
      'venv',
      'Diffs',
    ],
    directories: [
      'build',
      'node_modules',
      '__pycache__',
      'figures',
      'media',
      'figs',
      'versions',
      'history',
      'stuff',
      'draft',
      'miscellaneous',
      'diffs',
      'venv',
    ],
    keywords: [
      'Makefile',
      'template',
      '_thinking',
      '_diff',
      'draw',
      'versions',
      'history',
      '.egg-info',
      'venv',
      'yaml',
    ],
  },
} as const;
