/** Built-in file discovery rules. These are product behavior, not settings. */
export const FILE_HANDLING_RULES = Object.freeze({
  included: Object.freeze({
    mediaExtensions: Object.freeze([
      '.png',
      '.pdf',
      '.jpeg',
      '.jpg',
      '.gif',
      '.heic',
      '.heif',
      '.webp',
      '.wav',
      '.m4a',
      '.mp3',
      '.aiff',
      '.aac',
      '.opus',
      '.l16',
      '.alaw',
      '.mulaw',
      '.ogg',
      '.flac',
    ]),
    inputExtensions: Object.freeze(['.txt', '.tex', '.md']),
    contextExtensions: Object.freeze([
      '.txt',
      '.tex',
      '.md',
      '.bib',
      '.bbl',
      '.cls',
      '.sty',
    ]),
    editedExtensions: Object.freeze(['.txt', '.tex']),
  }),
  ignored: Object.freeze({
    fileExtensions: Object.freeze([
      '.pdf',
      '.bst',
      '.json',
      '.py',
      '.ipynb',
      '.png',
      '.vsix',
      '.ts',
      '.js',
      '.yaml',
    ]),
    inputFiles: Object.freeze([
      'command.tex',
      'commands.tex',
      'preamble.tex',
      'yaml',
    ]),
    inputDirectories: Object.freeze([]),
    mediaDirectories: Object.freeze([
      'build',
      'node_modules',
      '__pycache__',
      'versions',
      'history',
      'venv',
      'Diffs',
    ]),
    directories: Object.freeze([
      'build',
      'node_modules',
      '__pycache__',
      'figures',
      'media',
      'figs',
      'versions',
      'history',
      'stuff',
      'draft',
      'miscellaneous',
      'diffs',
      'venv',
    ]),
    keywords: Object.freeze([
      'Makefile',
      'template',
      '_thinking',
      '_diff',
      'draw',
      'versions',
      'history',
      '.egg-info',
      'venv',
      'yaml',
    ]),
  }),
});
