"""Registry of available model configurations."""

from .model_config import ModelConfig, ModelProvider, ModelCapabilities


MODEL_CONFIGS: dict[str, ModelConfig] = {
    # ===== Anthropic Claude Models =====
    "opus": ModelConfig(
        name="opus",
        fullName="claude-3-opus-20240229",
        openrouterFullName="anthropic/claude-3-opus:beta",
        provider=ModelProvider.ANTHROPIC,
        maxOutputTokens=4096,
        contextWindow=200000,
        inputPrice=15.0,
        outputPrice=75.0,
        capabilities=ModelCapabilities(supportsPromptCaching=True, supportsAssistantPrefill=True),
    ),
    "sonnet++": ModelConfig(
        name="sonnet++",
        fullName="claude-3-5-sonnet-20241022",
        openrouterFullName="anthropic/claude-3.5-sonnet:beta",
        provider=ModelProvider.ANTHROPIC,
        maxOutputTokens=8192,
        contextWindow=200000,
        inputPrice=3.0,
        outputPrice=15.0,
        capabilities=ModelCapabilities(
            supportsPromptCaching=True,
            supportsAssistantPrefill=True,
            supportsNativePdf=True,
            likesToAskForConfirmation=True,
        ),
    ),
    "sonnet+": ModelConfig(
        name="sonnet+",
        fullName="claude-3-5-sonnet-20240620",
        openrouterFullName="anthropic/claude-3.5-sonnet-20240620:beta",
        provider=ModelProvider.ANTHROPIC,
        maxOutputTokens=8192,
        contextWindow=200000,
        inputPrice=3.0,
        outputPrice=15.0,
        capabilities=ModelCapabilities(supportsPromptCaching=True, supportsAssistantPrefill=True),
    ),
    "sonnet": ModelConfig(
        name="sonnet",
        fullName="claude-3-sonnet-20240229",
        openrouterFullName="anthropic/claude-3.5-sonnet-20240229:beta",
        provider=ModelProvider.ANTHROPIC,
        maxOutputTokens=8192,
        contextWindow=200000,
        inputPrice=3.0,
        outputPrice=15.0,
        capabilities=ModelCapabilities(supportsAssistantPrefill=True),
    ),
    "haiku+": ModelConfig(
        name="haiku+",
        fullName="claude-3-5-haiku-20241022",
        openrouterFullName="anthropic/claude-3.5-haiku:beta",
        provider=ModelProvider.ANTHROPIC,
        maxOutputTokens=8192,
        contextWindow=200000,
        inputPrice=1.0,
        outputPrice=5.0,
        capabilities=ModelCapabilities(
            supportsPromptCaching=True,
            supportsAssistantPrefill=True,
            supportsVision=False,
            likesToAskForConfirmation=True,
        ),
    ),
    "haiku": ModelConfig(
        name="haiku",
        fullName="claude-3-haiku-20240307",
        openrouterFullName="anthropic/claude-3.5-haiku-20240307:beta",
        provider=ModelProvider.ANTHROPIC,
        maxOutputTokens=8192,
        contextWindow=200000,
        inputPrice=0.25,
        outputPrice=1.25,
        capabilities=ModelCapabilities(supportsPromptCaching=True, supportsAssistantPrefill=True),
    ),
    # ===== OpenAI Reasoning Models =====
    "o1": ModelConfig(
        name="o1",
        fullName="o1-2024-12-17",
        openrouterFullName="openai/o1-2024-12-17",
        provider=ModelProvider.OPENAI,
        maxOutputTokens=100000,
        contextWindow=200000,
        inputPrice=15.0,
        outputPrice=60.0,
        capabilities=ModelCapabilities(
            supportsAutoPromptCaching=True,
            supportsVision=True,
            supportsReasoning=True,
        ),
    ),
    "o1preview": ModelConfig(
        name="o1preview",
        fullName="o1-preview-2024-09-12",
        openrouterFullName="openai/o1-preview-2024-09-12",
        provider=ModelProvider.OPENAI,
        maxOutputTokens=32768,
        contextWindow=128000,
        inputPrice=15.0,
        outputPrice=60.0,
        capabilities=ModelCapabilities(
            supportsAutoPromptCaching=True,
            supportsVision=False,
            supportsReasoning=True,
        ),
    ),
    "o1-": ModelConfig(
        name="o1-",
        fullName="o1-mini-2024-09-12",
        openrouterFullName="openai/o1-mini-2024-09-12",
        provider=ModelProvider.OPENAI,
        maxOutputTokens=65536,
        contextWindow=128000,
        inputPrice=3.0,
        outputPrice=12.0,
        capabilities=ModelCapabilities(
            supportsAutoPromptCaching=True,
            supportsVision=False,
            supportsReasoning=True,
        ),
    ),
    # ===== OpenAI Models =====
    "gpt4o": ModelConfig(
        name="gpt4o",
        fullName="gpt-4o-2024-08-06",
        openrouterFullName="openai/gpt-4o-2024-08-06",
        provider=ModelProvider.OPENAI,
        maxOutputTokens=16384,
        contextWindow=128000,
        inputPrice=2.5,
        outputPrice=10.0,
        capabilities=ModelCapabilities(
            supportsAutoPromptCaching=True,
            upportsPredictiveOutput=True,
        ),
    ),
    "gpt4t": ModelConfig(
        name="gpt4t",
        fullName="gpt-4-turbo-2024-04-09",
        openrouterFullName="openai/gpt-4-turbo-2024-04-09",
        provider=ModelProvider.OPENAI,
        maxOutputTokens=4096,
        contextWindow=128000,
        inputPrice=10.0,
        outputPrice=30.0,
        capabilities=ModelCapabilities(supportsAutoPromptCaching=False, supportsReasoning=False),
    ),
    "gpt4o-": ModelConfig(
        name="gpt4o-",
        fullName="gpt-4o-mini-2024-07-18",
        openrouterFullName="openai/gpt-4o-mini-2024-07-18",
        provider=ModelProvider.OPENAI,
        maxOutputTokens=16384,
        contextWindow=128000,
        inputPrice=0.15,
        outputPrice=0.6,
        capabilities=ModelCapabilities(supportsAutoPromptCaching=True, upportsPredictiveOutput=True),
    ),
    "gpt4ol": ModelConfig(
        name="gpt4ol",
        fullName="chatgpt-4o-latest",
        openrouterFullName="openai/chatgpt-4o-latest",
        provider=ModelProvider.OPENAI,
        maxOutputTokens=16384,
        contextWindow=128000,
        inputPrice=5.0,
        outputPrice=15.0,
        capabilities=ModelCapabilities(supportsAutoPromptCaching=True, supportsReasoning=True),
    ),
    # ===== Google Gemini Models =====
    "geminiexp": ModelConfig(
        name="geminiexp",
        fullName="gemini-exp-1206",
        openrouterFullName="google/gemini-1.5-pro-exp-0120",
        provider=ModelProvider.GOOGLE,
        maxOutputTokens=4096,
        contextWindow=2097152,
        inputPrice=1.25,
        outputPrice=5.0,
        capabilities=ModelCapabilities(supportsVision=True),
    ),
    "gemini2fthinking": ModelConfig(
        name="gemini2fthinking",
        fullName="gemini-2.0-flash-thinking-exp-1219",
        openrouterFullName="google/gemini-2.0-flash-thinking-exp-1219",
        provider=ModelProvider.GOOGLE,
        maxOutputTokens=8192,
        contextWindow=32768,
        inputPrice=0.075,
        outputPrice=0.3,
        capabilities=ModelCapabilities(supportsNativePdf=False, supportsVision=True),
    ),
    "gemini2f": ModelConfig(
        name="gemini2f",
        fullName="gemini-2.0-flash-exp",
        openrouterFullName="google/gemini-2.0-flash-exp",
        provider=ModelProvider.GOOGLE,
        maxOutputTokens=8192,
        contextWindow=1048576,
        inputPrice=0.075,
        outputPrice=0.3,
        capabilities=ModelCapabilities(supportsNativePdf=True, supportsVision=True),
    ),
    "gemini1p+": ModelConfig(
        name="gemini1p+",
        fullName="gemini-1.5-pro-latest",
        openrouterFullName="google/gemini-1.5-pro-latest",
        provider=ModelProvider.GOOGLE,
        maxOutputTokens=8192,
        contextWindow=1048576,
        inputPrice=1.25,
        outputPrice=5.0,
        capabilities=ModelCapabilities(supportsNativePdf=True, supportsVision=True),
    ),
    "gemini1f+": ModelConfig(
        name="gemini1f+",
        fullName="gemini-1.5-fresh-latest",
        openrouterFullName="google/gemini-1.5-fresh-latest",
        provider=ModelProvider.GOOGLE,
        maxOutputTokens=8192,
        contextWindow=1048576,
        inputPrice=0.075,
        outputPrice=0.3,
        capabilities=ModelCapabilities(supportsNativePdf=True, supportsVision=True),
    ),
    # ===== OpenRouter Models =====
    "llama3+": ModelConfig(
        name="llama3+",
        fullName="meta-llama/llama-3.1-405b-instruct",
        provider=ModelProvider.OTHERS,
        openRouterOnly=True,
        openrouterFullName="meta-llama/llama-3.1-405b-instruct",
        maxOutputTokens=131072,
        contextWindow=131072,
        inputPrice=3.0,
        outputPrice=3.0,
    ),
    "qwq-32b": ModelConfig(
        name="qwq-32b",
        fullName="qwen/qwq-32b-preview",
        provider=ModelProvider.OTHERS,
        openRouterOnly=True,
        openrouterFullName="qwen/qwq-32b-preview",
        maxOutputTokens=32768,
        contextWindow=32768,
        inputPrice=0.15,
        outputPrice=0.6,
        capabilities=ModelCapabilities(supportsReasoning=True),
    ),
}
