import { mkdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { toErrorMessage } from '@common/errors/errorMessage';

import { CliExitCode } from '../runtime/exitCodes';
import { writeTextStderr, writeTextStdout } from '../runtime/logSinks';
import {
  currentBranch,
  defaultBranch,
  gh,
  ghAvailable,
  git,
  isGitRepo,
  localBranchExists,
  parseGitHubSlug,
  remoteUrl,
  repoRoot,
  type GitHubSlug,
} from '../runtime/gitOps';

import { defineCliCommand } from './_helpers/defineCliCommand';
import { GLOBAL_ARGS, optString } from './_helpers/globalArgs';
import type { CliContext } from '../runtime/cliContext';

const WORKFLOW_RELATIVE_PATH = '.github/workflows/texra-code-review.yml';
const DEFAULT_BRANCH_NAME = 'texra/add-code-review';

// Single-quoted lines keep the GitHub `${{ ... }}` expressions literal (a
// template literal would try to interpolate them).
const WORKFLOW_TEMPLATE = [
  '# Added by `texra install-github-action`. TeXRA reviews every pull request.',
  '# Docs: https://github.com/texra-ai/texra-action',
  'name: TeXRA Code Review',
  '',
  'on:',
  '  pull_request:',
  '    types: [opened, synchronize, ready_for_review, reopened]',
  '',
  'concurrency:',
  '  group: texra-review-${{ github.event.pull_request.number }}',
  '  cancel-in-progress: true',
  '',
  'jobs:',
  '  review:',
  '    # Disable without deleting the file: set repo variable TEXRA_REVIEW_ENABLED=false.',
  "    if: ${{ vars.TEXRA_REVIEW_ENABLED != 'false' }}",
  '    runs-on: ubuntu-latest',
  '    permissions:',
  '      contents: read',
  '      pull-requests: write',
  '    steps:',
  '      - name: Checkout pull request',
  '        uses: actions/checkout@v6',
  '        with:',
  '          # The merge ref + full history let the action compute merge-base..head.',
  '          ref: refs/pull/${{ github.event.pull_request.number }}/merge',
  '          fetch-depth: 0',
  '          persist-credentials: false',
  '',
  '      - name: Run TeXRA review',
  '        uses: texra-ai/texra-action/review@v1',
  '        with:',
  '          # Provide at least one provider key; the review model is auto-selected.',
  '          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}',
  '          # openai-api-key: ${{ secrets.OPENAI_API_KEY }}',
  '          # deepseek-api-key: ${{ secrets.DEEPSEEK_API_KEY }}',
  '          # Optional: pin the review model and CLI version.',
  '          # model: ${{ vars.TEXRA_REVIEW_MODEL }}',
  '          # texra-version: 0.38.5',
  '',
].join('\n');

const PR_BODY = [
  'Adds a TeXRA code-review GitHub Action that reviews every pull request.',
  '',
  'Set a provider API key secret (e.g. `ANTHROPIC_API_KEY`) so the review can run.',
  'Disable without deleting by setting repo variable `TEXRA_REVIEW_ENABLED=false`.',
  '',
  'Generated by `texra install-github-action`.',
].join('\n');

interface InstallOptions {
  readonly branch: string | undefined;
  readonly base: string | undefined;
  readonly force: boolean;
  readonly openPr: boolean;
}

async function pathExists(target: string): Promise<boolean> {
  try {
    await stat(target);
    return true;
  } catch {
    return false;
  }
}

function compareUrl(slug: GitHubSlug, base: string, branch: string): string {
  return `https://github.com/${slug.owner}/${slug.repo}/compare/${base}...${branch}?expand=1`;
}

function restoreBranch(cwd: string, branch: string | null): void {
  if (branch) git(cwd, 'checkout', branch);
}

function printSecretChecklist(slug: GitHubSlug | null): void {
  const repoFlag = slug ? ` -R ${slug.owner}/${slug.repo}` : '';
  writeTextStdout('');
  writeTextStdout('Next — set a provider API key so the review can run:');
  writeTextStdout(`  gh secret set ANTHROPIC_API_KEY${repoFlag}`);
  writeTextStdout(
    'TeXRA auto-selects the model from whichever key is set (ANTHROPIC_API_KEY,',
  );
  writeTextStdout(
    'OPENAI_API_KEY, DEEPSEEK_API_KEY, GOOGLE_API_KEY, OPENROUTER_API_KEY).',
  );
}

async function runInstallGithubAction(
  context: CliContext,
  opts: InstallOptions,
): Promise<number> {
  const { cwd } = context;

  if (!isGitRepo(cwd)) {
    writeTextStderr(
      'Not inside a git repository. Run this from a cloned GitHub repo.',
    );
    return CliExitCode.Usage;
  }

  const root = repoRoot(cwd) ?? cwd;
  const workflowAbsPath = path.join(root, WORKFLOW_RELATIVE_PATH);

  if ((await pathExists(workflowAbsPath)) && !opts.force) {
    writeTextStderr(
      `${WORKFLOW_RELATIVE_PATH} already exists. Re-run with --force to overwrite it.`,
    );
    return CliExitCode.Usage;
  }

  const url = remoteUrl(root);
  const slug = url ? parseGitHubSlug(url) : null;
  const base = opts.base ?? defaultBranch(root) ?? 'main';
  const branch = opts.branch ?? DEFAULT_BRANCH_NAME;
  const startBranch = currentBranch(root);

  const branchExists = localBranchExists(root, branch);
  if (branchExists && !opts.force) {
    writeTextStderr(
      `Branch "${branch}" already exists. Pass --branch <name> or --force.`,
    );
    return CliExitCode.Usage;
  }

  const checkout = branchExists
    ? git(root, 'checkout', '-B', branch)
    : git(root, 'checkout', '-b', branch);
  if (!checkout.ok) {
    writeTextStderr(`Failed to create branch "${branch}": ${checkout.stderr}`);
    return CliExitCode.AgentError;
  }

  try {
    await mkdir(path.dirname(workflowAbsPath), { recursive: true });
    await writeFile(workflowAbsPath, WORKFLOW_TEMPLATE, 'utf8');
  } catch (error) {
    writeTextStderr(
      `Failed to write ${WORKFLOW_RELATIVE_PATH}: ${toErrorMessage(error)}`,
    );
    restoreBranch(root, startBranch);
    return CliExitCode.AgentError;
  }

  const add = git(root, 'add', '--', WORKFLOW_RELATIVE_PATH);
  const commit = add.ok
    ? git(root, 'commit', '-m', 'ci: add TeXRA code-review workflow')
    : add;
  if (!commit.ok) {
    writeTextStderr(`Failed to commit the workflow: ${commit.stderr}`);
    restoreBranch(root, startBranch);
    return CliExitCode.AgentError;
  }

  writeTextStdout(`Created ${WORKFLOW_RELATIVE_PATH} on branch "${branch}".`);

  if (!opts.openPr) {
    writeTextStdout(
      `Skipped push/PR (--no-pr). Push "${branch}" and open a PR when ready.`,
    );
    printSecretChecklist(slug);
    return CliExitCode.Success;
  }

  if (!slug) {
    writeTextStdout(
      'No GitHub "origin" remote detected — committed to the new branch locally.',
    );
    writeTextStdout(
      `Push "${branch}" to your GitHub remote and open a PR manually.`,
    );
    restoreBranch(root, startBranch);
    printSecretChecklist(slug);
    return CliExitCode.Success;
  }

  const push = git(root, 'push', '-u', 'origin', branch);
  if (!push.ok) {
    writeTextStderr(`Failed to push "${branch}": ${push.stderr}`);
    writeTextStdout(`Open a PR manually: ${compareUrl(slug, base, branch)}`);
    restoreBranch(root, startBranch);
    printSecretChecklist(slug);
    return CliExitCode.Success;
  }

  if (ghAvailable(root)) {
    const pr = gh(
      root,
      'pr',
      'create',
      '--base',
      base,
      '--head',
      branch,
      '--title',
      'Add TeXRA code review',
      '--body',
      PR_BODY,
    );
    if (pr.ok) {
      writeTextStdout(`Opened pull request:\n${pr.stdout}`);
    } else {
      writeTextStderr(`gh pr create failed: ${pr.stderr}`);
      writeTextStdout(`Open a PR manually: ${compareUrl(slug, base, branch)}`);
    }
  } else {
    writeTextStdout(
      `gh CLI not found. Branch pushed — open a PR here:\n${compareUrl(slug, base, branch)}`,
    );
  }

  restoreBranch(root, startBranch);
  printSecretChecklist(slug);
  return CliExitCode.Success;
}

export const installGithubActionCommand = defineCliCommand({
  meta: {
    name: 'install-github-action',
    description: 'Scaffold the TeXRA code-review GitHub Action and open a PR',
  },
  args: {
    ...GLOBAL_ARGS,
    branch: {
      type: 'string',
      description: `Branch to create for the PR (default: ${DEFAULT_BRANCH_NAME})`,
    },
    base: {
      type: 'string',
      description: 'Base branch for the PR (default: the repo default branch)',
    },
    force: {
      type: 'boolean',
      description: 'Overwrite an existing workflow file / reuse the branch',
    },
    pr: {
      type: 'boolean',
      default: true,
      negativeDescription: 'Only scaffold and commit; do not push or open a PR',
      description: 'Push the branch and open a pull request',
    },
  },
  run: (context, ctx) =>
    runInstallGithubAction(context, {
      branch: optString(ctx.args.branch),
      base: optString(ctx.args.base),
      force: ctx.args.force === true,
      openPr: ctx.args.pr !== false,
    }),
  catchExitCode: CliExitCode.AgentError,
});
