import { mkdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { toErrorMessage } from '@utils/errors/errorMessage';

import { CliExitCode } from '../runtime/exitCodes';
import { tryOpenBrowser } from '../runtime/browser';
import { writeTextStderr, writeTextStdout } from '../runtime/logSinks';
import {
  currentBranch,
  defaultBranch,
  gh,
  ghAvailable,
  git,
  isGitRepo,
  localBranchExists,
  parseGitHubSlug,
  remoteUrl,
  repoRoot,
  type GitHubSlug,
} from '../runtime/gitOps';

import { defineCliCommand } from './_helpers/defineCliCommand';
import { GLOBAL_ARGS, optString } from './_helpers/globalArgs';
import type { CliContext } from '../runtime/cliContext';

const WORKFLOW_RELATIVE_PATH = '.github/workflows/texra-code-review.yml';
const DEFAULT_BRANCH_NAME = 'texra/add-code-review';
const TEXRA_GITHUB_APP_INSTALL_URL =
  'https://github.com/apps/texra-ai-bot/installations/new';

// Single-quoted lines keep the GitHub `${{ ... }}` expressions literal (a
// template literal would try to interpolate them).
const WORKFLOW_TEMPLATE = [
  '# Added by `texra install-github-action`. TeXRA reviews every pull request.',
  '# Docs: https://texra.ai/guide/code-review',
  'name: TeXRA Code Review',
  '',
  'on:',
  '  pull_request:',
  '    types: [opened, synchronize, ready_for_review, reopened]',
  '',
  'concurrency:',
  '  group: texra-review-${{ github.event.pull_request.number }}',
  '  cancel-in-progress: true',
  '',
  'jobs:',
  '  review:',
  '    # Disable without deleting the file: set repo variable TEXRA_REVIEW_ENABLED=false.',
  "    if: ${{ vars.TEXRA_REVIEW_ENABLED != 'false' }}",
  '    runs-on: ubuntu-latest',
  '    permissions:',
  '      contents: read',
  '      pull-requests: write',
  '      id-token: write',
  '    steps:',
  '      - name: Checkout pull request',
  '        uses: actions/checkout@v6',
  '        with:',
  '          # The merge ref + full history let the action compute merge-base..head.',
  '          ref: refs/pull/${{ github.event.pull_request.number }}/merge',
  '          fetch-depth: 0',
  '          persist-credentials: false',
  '',
  '      - name: Run TeXRA review',
  '        # Customers track @v1; dogfood/repro pins use a full commit SHA instead.',
  '        uses: texra-ai/texra-action/review@v1',
  '        with:',
  '          require-write-access: "true"',
  '          allow-bots: dependabot[bot]',
  '          resolve-threads: "true"',
  '          # Provide at least one provider key; open-weight defaults first.',
  '          deepseek-api-key: ${{ secrets.DEEPSEEK_API_KEY }}',
  '          openrouter-api-key: ${{ secrets.OPENROUTER_API_KEY }}',
  '          google-api-key: ${{ secrets.GOOGLE_API_KEY }}',
  '          openai-api-key: ${{ secrets.OPENAI_API_KEY }}',
  '          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}',
  '          xai-api-key: ${{ secrets.XAI_API_KEY }}',
  '          # Optional: pin the review model and CLI version.',
  '          # model: ${{ vars.TEXRA_REVIEW_MODEL }}',
  '          # texra-version: 0.38.5',
  '',
].join('\n');

const PR_BODY = [
  'Adds a TeXRA code-review GitHub Action that reviews every pull request.',
  '',
  'The workflow authenticates through the installed TeXRA GitHub App using a short-lived OIDC token.',
  'Set a provider API key secret (e.g. `DEEPSEEK_API_KEY`) so the review can run.',
  'Disable without deleting by setting repo variable `TEXRA_REVIEW_ENABLED=false`.',
  '',
  'Generated by `texra install-github-action`.',
].join('\n');

interface InstallOptions {
  readonly branch: string | undefined;
  readonly base: string | undefined;
  readonly force: boolean;
  readonly openPr: boolean;
}

async function pathExists(target: string): Promise<boolean> {
  try {
    await stat(target);
    return true;
  } catch {
    return false;
  }
}

function compareUrl(slug: GitHubSlug, base: string, branch: string): string {
  const range = `${encodeURIComponent(base)}...${encodeURIComponent(branch)}`;
  return `https://github.com/${slug.owner}/${slug.repo}/compare/${range}?expand=1`;
}

function refExists(cwd: string, ref: string): boolean {
  return git(cwd, 'rev-parse', '--verify', '--quiet', `${ref}^{commit}`)
    .success;
}

function resolveBaseRef(cwd: string, base: string): string | null {
  if (refExists(cwd, base)) return base;
  const originRef = `origin/${base}`;
  return refExists(cwd, originRef) ? originRef : null;
}

function restoreBranch(cwd: string, branch: string | null): void {
  if (branch) git(cwd, 'checkout', branch);
}

function printSecretChecklist(slug: GitHubSlug | null): void {
  const repoFlag = slug ? ` -R ${slug.owner}/${slug.repo}` : '';
  writeTextStdout('');
  writeTextStdout('Next — set a provider API key so the review can run:');
  writeTextStdout(`  gh secret set DEEPSEEK_API_KEY${repoFlag}`);
  writeTextStdout(
    'Prefer an open-weight provider when you can. TeXRA auto-selects from',
  );
  writeTextStdout(
    'whichever key is set (DeepSeek → Anthropic → OpenAI → Google → OpenRouter → xAI).',
  );
}

async function openGitHubAppInstaller(slug: GitHubSlug | null): Promise<void> {
  if (!slug) return;

  const opened = await tryOpenBrowser(TEXRA_GITHUB_APP_INSTALL_URL);
  writeTextStdout('');
  if (opened) {
    writeTextStdout(
      `Opened the TeXRA GitHub App installer. Grant it access to ${slug.owner}/${slug.repo}.`,
    );
  } else {
    writeTextStdout(
      `Install the TeXRA GitHub App on ${slug.owner}/${slug.repo}:\n${TEXRA_GITHUB_APP_INSTALL_URL}`,
    );
  }
}

async function runInstallGithubAction(
  context: CliContext,
  opts: InstallOptions,
): Promise<number> {
  const { cwd } = context;

  if (!isGitRepo(cwd)) {
    writeTextStderr(
      'Not inside a git repository. Run this from a cloned GitHub repo.',
    );
    return CliExitCode.Usage;
  }

  const root = repoRoot(cwd) ?? cwd;
  const workflowAbsPath = path.join(root, WORKFLOW_RELATIVE_PATH);

  if ((await pathExists(workflowAbsPath)) && !opts.force) {
    writeTextStderr(
      `${WORKFLOW_RELATIVE_PATH} already exists. Re-run with --force to overwrite it.`,
    );
    return CliExitCode.Usage;
  }

  const url = remoteUrl(root);
  const slug = url ? parseGitHubSlug(url) : null;
  await openGitHubAppInstaller(slug);
  const base = opts.base ?? defaultBranch(root) ?? 'main';
  const branch = opts.branch ?? DEFAULT_BRANCH_NAME;
  const startBranch = currentBranch(root);

  const branchExists = localBranchExists(root, branch);
  if (branchExists && !opts.force) {
    writeTextStderr(
      `Branch "${branch}" already exists. Pass --branch <name> or --force.`,
    );
    return CliExitCode.Usage;
  }

  let checkout: ReturnType<typeof git>;
  if (branchExists) {
    checkout = git(root, 'checkout', branch);
  } else {
    const baseRef = resolveBaseRef(root, base);
    if (!baseRef) {
      writeTextStderr(
        `Could not resolve base branch "${base}". Fetch it or pass --base <branch>.`,
      );
      return CliExitCode.Usage;
    }
    checkout = git(root, 'checkout', '-b', branch, baseRef);
  }
  if (!checkout.success) {
    writeTextStderr(
      `Failed to check out branch "${branch}": ${checkout.stderr ?? ''}`,
    );
    return CliExitCode.AgentError;
  }

  // Report the failure, put the user back on the branch they started from, and
  // hand back the error exit code.
  const abort = (message: string): number => {
    writeTextStderr(message);
    restoreBranch(root, startBranch);
    return CliExitCode.AgentError;
  };

  try {
    await mkdir(path.dirname(workflowAbsPath), { recursive: true });
    await writeFile(workflowAbsPath, WORKFLOW_TEMPLATE, 'utf8');
  } catch (error) {
    return abort(
      `Failed to write ${WORKFLOW_RELATIVE_PATH}: ${toErrorMessage(error)}`,
    );
  }

  const add = git(root, 'add', '--', WORKFLOW_RELATIVE_PATH);
  if (!add.success) {
    return abort(`Failed to stage the workflow: ${add.stderr ?? ''}`);
  }

  const diff = git(
    root,
    'diff',
    '--cached',
    '--quiet',
    '--',
    WORKFLOW_RELATIVE_PATH,
  );
  if (diff.exitCode !== 0 && diff.exitCode !== 1) {
    return abort(
      `Failed to inspect staged workflow changes: ${diff.stderr ?? ''}`,
    );
  }

  const hasWorkflowChanges = diff.exitCode === 1;
  if (hasWorkflowChanges) {
    const commit = git(
      root,
      'commit',
      '-m',
      'ci: add TeXRA code-review workflow',
      '--',
      WORKFLOW_RELATIVE_PATH,
    );
    if (!commit.success) {
      return abort(`Failed to commit the workflow: ${commit.stderr ?? ''}`);
    }
    writeTextStdout(`Created ${WORKFLOW_RELATIVE_PATH} on branch "${branch}".`);
  } else {
    writeTextStdout(
      `${WORKFLOW_RELATIVE_PATH} already matches the TeXRA template on branch "${branch}".`,
    );
    if (!branchExists) {
      restoreBranch(root, startBranch);
      printSecretChecklist(slug);
      return CliExitCode.Success;
    }
  }

  if (!opts.openPr) {
    writeTextStdout(
      `Skipped push/PR (--no-pr). Push "${branch}" and open a PR when ready.`,
    );
    printSecretChecklist(slug);
    return CliExitCode.Success;
  }

  if (!slug) {
    writeTextStdout(
      'No GitHub "origin" remote detected — committed to the new branch locally.',
    );
    writeTextStdout(
      `Push "${branch}" to your GitHub remote and open a PR manually.`,
    );
    printSecretChecklist(slug);
    return CliExitCode.Success;
  }

  const push = git(root, 'push', '-u', 'origin', branch);
  if (!push.success) {
    writeTextStderr(`Failed to push "${branch}": ${push.stderr ?? ''}`);
    writeTextStdout(
      `Once pushed, open ${compareUrl(slug, base, branch)} to propose the PR.`,
    );
    printSecretChecklist(slug);
    return CliExitCode.AgentError;
  }

  // Open the PR-creation page in the browser and let the user review the diff
  // and propose the PR themselves, rather than creating it headlessly. Prefer
  // `gh pr create --web` (it prefills the title/body) and fall back to opening
  // the compare URL directly when gh is unavailable or cannot open the page.
  const prPageUrl = compareUrl(slug, base, branch);
  let opened: boolean;
  if (ghAvailable(root)) {
    const pr = gh(
      root,
      'pr',
      'create',
      '--web',
      '--base',
      base,
      '--head',
      branch,
      '--title',
      'Add TeXRA code review',
      '--body',
      PR_BODY,
    );
    opened = pr.success;
    if (!pr.success) {
      const diagnostic = pr.stderr ?? pr.stdout ?? '';
      writeTextStderr(
        diagnostic
          ? `gh pr create --web failed: ${diagnostic}`
          : 'gh pr create --web failed; opening the compare URL instead.',
      );
      opened = await tryOpenBrowser(prPageUrl);
    }
  } else {
    opened = await tryOpenBrowser(prPageUrl);
  }

  restoreBranch(root, startBranch);
  if (opened) {
    writeTextStdout(
      'Opened the pull-request page in your browser — review the diff and click "Create pull request".',
    );
  } else {
    writeTextStdout(
      `Branch pushed, but the browser did not open. Open this page to propose the PR:\n${prPageUrl}`,
    );
  }
  printSecretChecklist(slug);
  return CliExitCode.Success;
}

export const installGithubActionCommand = defineCliCommand({
  meta: {
    name: 'install-github-action',
    description: 'Install the TeXRA GitHub App and scaffold code review',
  },
  args: {
    ...GLOBAL_ARGS,
    branch: {
      type: 'string',
      description: `Branch to create for the PR (default: ${DEFAULT_BRANCH_NAME})`,
    },
    base: {
      type: 'string',
      description: 'Base branch for the PR (default: the repo default branch)',
    },
    force: {
      type: 'boolean',
      description: 'Overwrite an existing workflow file / reuse the branch',
    },
    pr: {
      type: 'boolean',
      default: true,
      negativeDescription: 'Only scaffold and commit; do not push or open a PR',
      description: 'Push the branch and open a pull request',
    },
  },
  run: (context, ctx) =>
    runInstallGithubAction(context, {
      branch: optString(ctx.args.branch),
      base: optString(ctx.args.base),
      force: ctx.args.force === true,
      openPr: ctx.args.pr !== false,
    }),
  catchExitCode: CliExitCode.AgentError,
});
