version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: '@types/node'
      - dependency-name: '@types/vscode'
    groups:
      dev-dependencies:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint*'
          - 'prettier'
        update-types:
          - 'minor'
          - 'patch'
