packages:
  - packages/*
supportedArchitectures:
  os:
    - current
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
allowBuilds:
  '@google/genai': true
  '@openrouter/sdk': true
  '@vscode/vsce-sign': true
  electron-winstaller: true
  esbuild: true
  keytar: true
  node-pty: true
  protobufjs: true
  unrs-resolver: true
patchedDependencies:
  ink@7.0.5: patches/ink@7.0.5.patch
