[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "coauthor"
version = "0.10.0"
authors = [
  { name="Sirui Lu", email="sirui.lu.phys@gmail.com" },
]
description = "A package containing utility functions for interacting with LLM models like Anthropic's Claude AI."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "termcolor",
    "requests",
    "openai",
    "anthropic",
    "IPython",
    "click",
    "PyMuPDF",
    "termcolor",
    "python-dotenv",
    "pillow",
]

[project.urls]
"Homepage" = "https://github.com/LionSR/coauthor"
"Bug Tracker" = "https://github.com/LionSR/coauthor/issues"

[tool.setuptools]
packages = ["coauthor"]

[project.entry-points.console_scripts]
coauthor = "coauthor.cli:cli"

[tool.black]
line-length = 151
target-version = ['py39', 'py310', 'py311', 'py312']
include = '\.(pyi?|ipynb)$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''