// Supabase Edge Function: log-proxy-usage
//
// Records billing events generated by proxy-backed model executions. Payloads
// are emitted by the VS Code extension whenever a proxy session is active.
import type {
  Serve,
  RequestHandler,
} from 'https://esm.sh/@supabase/functions@2.4.1';

interface UsageEvent {
  provider: string;
  model: string;
  cost: number;
  usage: Record<string, unknown>;
  proxySessionId?: string;
}

const serve: Serve = async (req) => {
  const headers = new Headers({ 'Content-Type': 'application/json' });

  try {
    const payload = (await req.json()) as UsageEvent;

    if (!payload || !payload.provider || !payload.model) {
      return new Response(JSON.stringify({ error: 'Invalid payload' }), {
        headers,
        status: 400,
      });
    }

    // TODO: persist the billing event in Supabase (e.g., insert into proxy_usage).
    // Suggested schema:
    //   account_id UUID REFERENCES auth.users
    //   proxy_session_id TEXT
    //   provider TEXT
    //   model TEXT
    //   cost NUMERIC
    //   usage JSONB
    //   created_at TIMESTAMP WITH TIME ZONE DEFAULT now()

    return new Response(JSON.stringify({ status: 'ok' }), {
      headers,
      status: 200,
    });
  } catch (err) {
    return new Response(
      JSON.stringify({
        error: err instanceof Error ? err.message : String(err),
      }),
      { headers, status: 500 },
    );
  }
};

export const handler: RequestHandler = serve;
