-- Auto-generated by scripts/sync-remote-agents.mjs.
-- Source of truth: prompts/agents/remote/**/*.yaml.
-- Run `npm run sync:remote-agents` to refresh this file.

ALTER TABLE remote_agents
ADD COLUMN IF NOT EXISTS tools TEXT[] DEFAULT NULL;

-- ---------------------------------------------------------------------------
-- Workflow agents
-- ---------------------------------------------------------------------------

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'apply',
  'Implements suggestions from review agents (criticize, enhance, logic, notation, etc.). Reads inline annotations, works through the issues, and applies corrections.',
  'researcher/apply.yaml',
  ARRAY['public'],
  'workflow',
  NULL
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'criticize',
  'Critical reviewer for mathematical physics papers. Inserts inline comments using \criticize{}{severity}{confidence} without modifying original content.',
  'QITBench/criticize.yaml',
  ARRAY['whitelist', 'QITBench', 'researcher', 'public'],
  'workflow',
  NULL
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'devise',
  'Mathematical paper enhancer with two-phase workflow. Rewrites document(s) by first adding rigorous derivations then revising to publication-ready scientific style.',
  'QITBench/devise.yaml',
  ARRAY['researcher', 'QITBench', 'public'],
  'workflow',
  NULL
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'elevate',
  'Revises academic papers for publication in two phases. Checks the argument for editors, specialists, adjacent-field reviewers, and non-specialists. Applies clear local improvements and marks strategic decisions with \criticize{}{}{} comments for author review.',
  'researcher/elevate.yaml',
  ARRAY['researcher'],
  'workflow',
  NULL
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'enhance',
  'Mathematical substance enhancer for research papers. Identifies elegant proofs and stronger results.',
  'whitelist/enhance.yaml',
  ARRAY['public'],
  'workflow',
  NULL
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'firstread',
  'First-read pass by a naive linear physicist reading the paper top-to-bottom for the first time. Emits inline \criticize{message}{severity}{confidence} annotations at every reader stop (undefined terms, forward references, unclear citations, missing baselines, logical-coverage gaps, unsupported claims, unparseable or nonsensical prose, AI-jargon, oversold tone, duplicates, process claims to verify, and domain claims needing support). Every annotation pairs the stop with a concrete fix. Output is a self-contained compile-ready LaTeX document.',
  'researcher/firstread.yaml',
  ARRAY['public'],
  'workflow',
  NULL
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'generic',
  'General-purpose LaTeX document editor. Flexibly processes research papers following academic standards and user instructions. Detects and uses existing comment styles (\todo, \comment, %).',
  'public/generic.yaml',
  ARRAY['public'],
  'workflow',
  NULL
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'humanize',
  'Removes LLM stylistic tells from research prose. Phase 1 annotates problems. Phase 2 directly rewrites for natural voice while strictly preserving meaning.',
  'researcher/humanize.yaml',
  ARRAY['researcher'],
  'workflow',
  NULL
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'logic',
  'Logical flow analyzer for research papers. Improves argument structure and coherence.',
  'researcher/logic.yaml',
  ARRAY['public'],
  'workflow',
  NULL
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'notation',
  'Notation consistency checker for research papers. Ensures consistent symbol usage throughout documents.',
  'researcher/notation.yaml',
  ARRAY['public'],
  'workflow',
  NULL
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'verifyFix',
  'Three-phase verification and fix agent for research papers. Expands, critiques with verification, then fixes with documentation.',
  'researcher/verifyFix.yaml',
  ARRAY['researcher'],
  'workflow',
  NULL
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

-- ---------------------------------------------------------------------------
-- Tool-use agents
-- ---------------------------------------------------------------------------

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'orchestrator',
  'Coordinates multi-agent work on LaTeX research projects. It reads project context, turns broad goals into focused tasks, routes each task to the right specialist, tracks results, reviews generated files, and keeps follow-up work organized.',
  'tool-use/orchestrator.yaml',
  ARRAY['public'],
  'toolUse',
  ARRAY['delegate_workflow', 'delegate_agent', 'executions', 'accept_run_files', 'delegate_multi_agents', 'todo_write', 'plan', 'read_file', 'write_file', 'edit_file', 'bash', 'glob', 'grep', 'extract_figures', 'extract_bib_entries', 'texcount', 'inquiry', 'codex', 'claude_code', 'github_subscription']
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'presenter',
  'Interactive scientific presentation builder with visual QA.',
  'tool-use/presenter.yaml',
  ARRAY['public'],
  'toolUse',
  ARRAY['todo_write', 'bash', 'read_file', 'write_file', 'edit_file', 'glob', 'grep', 'extract_figures', 'extract_bib_entries', 'extract_tikz_figures', 'wolfram', 'arxiv_search', 'arxiv_metadata', 'web_search', 'web_fetch']
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'progressCheck',
  'End-of-session reviewer. Looks at what was just done and, when relevant, the project''s standing goal and git/PR state to decide whether the orchestrator is actually finished or whether meaningful, low-risk progress is still sitting on the table. Read-only. Advises without editing or delegating.',
  'tool-use/progressCheck.yaml',
  ARRAY['public'],
  'toolUse',
  ARRAY['executions', 'read_file', 'glob', 'grep', 'bash', 'memory', 'github_subscription', 'web_fetch', 'inquiry']
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'search',
  'Research assistant with web search and literature discovery tools.',
  'tool-use/search.yaml',
  ARRAY['public'],
  'toolUse',
  ARRAY['bash', 'read_file', 'glob', 'grep', 'extract_figures', 'extract_bib_entries', 'extract_tikz_figures', 'arxiv_search', 'arxiv_metadata', 'download_arxiv_source', 'crossref_search', 'zotero_add', 'zotero_search', 'zotero_export', 'web_search', 'web_fetch']
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'simplifier',
  'Simplifies scientific code and LaTeX for clarity and maintainability while preserving all functionality.',
  'tool-use/simplifier.yaml',
  ARRAY['public'],
  'toolUse',
  ARRAY['todo_write', 'bash', 'read_file', 'write_file', 'edit_file', 'glob', 'grep', 'diagnostics', 'extract_figures', 'extract_tikz_figures', 'memory']
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

-- ---------------------------------------------------------------------------
-- Tool-use agents (Lean)
-- ---------------------------------------------------------------------------

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'lean',
  'Lean 4 proof assistant with VS Code integration and CLI fallback.',
  'tool-use-lean/lean.yaml',
  ARRAY['researcher', 'lean'],
  'toolUse',
  ARRAY['todo_write', 'lean_diagnostics', 'lean_file', 'lean_project', 'lean_inspect', 'lean_loogle', 'bash', 'read_file', 'write_file', 'edit_file', 'glob', 'grep', 'memory', 'github_subscription']
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'leanBlueprint',
  'Creates and maintains dependency-tracked LeanBlueprint documents that bridge informal mathematics and Lean 4 formalization.',
  'tool-use-lean/leanBlueprint.yaml',
  ARRAY['researcher', 'lean'],
  'toolUse',
  ARRAY['todo_write', 'bash', 'read_file', 'write_file', 'edit_file', 'glob', 'grep', 'memory', 'lean_diagnostics', 'lean_file', 'lean_project', 'lean_inspect', 'lean_loogle', 'web_search', 'web_fetch', 'arxiv_search', 'arxiv_metadata', 'download_arxiv_source', 'crossref_search', 'zotero_add', 'zotero_search', 'zotero_export']
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'leanOrchestrator',
  'Lean 4 project orchestrator. Coordinates formalization, delegates to specialized Lean agents, and manages proof development workflow.',
  'tool-use-lean/leanOrchestrator.yaml',
  ARRAY['researcher', 'lean'],
  'toolUse',
  ARRAY['delegate_workflow', 'delegate_agent', 'delegate_multi_agents', 'executions', 'accept_run_files', 'todo_write', 'plan', 'read_file', 'write_file', 'edit_file', 'bash', 'glob', 'grep', 'codex', 'claude_code', 'lean_diagnostics', 'lean_inspect', 'lean_loogle', 'lean_file', 'lean_project', 'github_subscription']
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'leanSearch',
  'Lean 4 and Mathlib research assistant. Finds lemmas, explores APIs, and answers formalization questions.',
  'tool-use-lean/leanSearch.yaml',
  ARRAY['researcher', 'lean'],
  'toolUse',
  ARRAY['todo_write', 'bash', 'read_file', 'write_file', 'edit_file', 'glob', 'grep', 'memory', 'lean_diagnostics', 'lean_file', 'lean_project', 'lean_inspect', 'lean_loogle', 'web_search', 'web_fetch', 'arxiv_search', 'arxiv_metadata', 'download_arxiv_source']
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

INSERT INTO remote_agents (name, description, storage_path, visibility, agent_category, tools)
VALUES (
  'leanSimplifier',
  'Simplifies Lean 4 proofs and code into clear, general, upstream-ready Mathlib style.',
  'tool-use-lean/leanSimplifier.yaml',
  ARRAY['researcher', 'lean'],
  'toolUse',
  ARRAY['todo_write', 'bash', 'read_file', 'write_file', 'edit_file', 'glob', 'grep', 'memory', 'lean_diagnostics', 'lean_file', 'lean_project', 'lean_inspect', 'lean_loogle']
)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  storage_path   = EXCLUDED.storage_path,
  visibility     = EXCLUDED.visibility,
  agent_category = EXCLUDED.agent_category,
  tools          = EXCLUDED.tools;

-- ---------------------------------------------------------------------------
-- Cleanup stale entries (renamed/removed agents)
-- ---------------------------------------------------------------------------

DELETE FROM remote_agents WHERE name IN ('apply_multiple', 'criticize_multiple', 'devise_multiple', 'elevate_multiple', 'enhance_multiple', 'generic_multiple', 'logic_multiple', 'notation_multiple', 'verifyFix_multiple');

-- Verify
SELECT name, description, agent_category, tools, visibility
FROM remote_agents
ORDER BY agent_category, name;
