/**
 * Registry of available language model configurations with pricing and capabilities.
 * Models are grouped by provider (Anthropic, OpenAI, Google) and include:
 * - Model identifiers and versions
 * - Context window and token limits
 * - Pricing for input/output tokens
 * - Provider-specific capabilities
 */

// Local imports - agent components
import {
  ModelConfig,
  ModelProvider,
  ModelCapabilities,
  DEFAULT_MODEL_CAPABILITIES,
} from './ModelConfig';

/**
 * Available model configurations indexed by short name.
 * Each configuration includes complete model settings and capabilities.
 */
export const MODEL_CONFIGS: Record<string, ModelConfig> = {
  // ===== Anthropic Claude Models =====
  'sonnet*T': {
    name: 'sonnet*T',
    fullName: 'claude-3-7-sonnet-20250219',
    openrouterFullName: 'anthropic/claude-3.7-sonnet',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 21333, // Using extended output with beta header
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAssistantPrefill: false,
      supportsNativePdf: true,
      supportsReasoning: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  'sonnet*': {
    name: 'sonnet*',
    fullName: 'claude-3-7-sonnet-20250219',
    openrouterFullName: 'anthropic/claude-3.7-sonnet',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 21333, // Using extended output with beta header
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAssistantPrefill: false,
      supportsNativePdf: true,
      supportsReasoning: false,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  opus: {
    name: 'opus',
    fullName: 'claude-3-opus-20240229',
    openrouterFullName: 'anthropic/claude-3-opus:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 4096,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAssistantPrefill: true,
      supportsTokenCounting: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  'sonnet++': {
    name: 'sonnet++',
    fullName: 'claude-3-5-sonnet-20241022',
    openrouterFullName: 'anthropic/claude-3.5-sonnet:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAssistantPrefill: true,
      supportsNativePdf: true,
      supportsTokenCounting: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  'sonnet+': {
    name: 'sonnet+',
    fullName: 'claude-3-5-sonnet-20240620',
    openrouterFullName: 'anthropic/claude-3.5-sonnet-20240620:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAssistantPrefill: true,
      supportsTokenCounting: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  sonnet: {
    name: 'sonnet',
    fullName: 'claude-3-sonnet-20240229',
    openrouterFullName: 'anthropic/claude-3.5-sonnet-20240229:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsAssistantPrefill: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  'haiku+': {
    name: 'haiku+',
    fullName: 'claude-3-5-haiku-20241022',
    openrouterFullName: 'anthropic/claude-3.5-haiku:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 1.0,
    outputPrice: 5.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAssistantPrefill: true,
      supportsVision: true,
      supportsTokenCounting: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  haiku: {
    name: 'haiku',
    fullName: 'claude-3-haiku-20240307',
    openrouterFullName: 'anthropic/claude-3.5-haiku-20240307:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 0.25,
    outputPrice: 1.25,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAssistantPrefill: true,
      supportsTokenCounting: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },

  // ===== OpenAI Reasoning Models =====
  'o3-': {
    name: 'o3-',
    fullName: 'o3-mini-2025-01-31',
    openrouterFullName: 'openai/o3-mini-2025-01-31',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 12.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsAutoPromptCaching: true,
      supportsVision: false,
      supportsReasoning: true,
      reasoning_effort: 'high',
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  o1: {
    name: 'o1',
    fullName: 'o1-2024-12-17',
    openrouterFullName: 'openai/o1-2024-12-17',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 60.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsAutoPromptCaching: true,
      supportsVision: true,
      supportsReasoning: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  o1preview: {
    name: 'o1preview',
    fullName: 'o1-preview-2024-09-12',
    openrouterFullName: 'openai/o1-preview-2024-09-12',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 32768,
    contextWindow: 128000,
    inputPrice: 15.0,
    outputPrice: 60.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsAutoPromptCaching: true,
      supportsVision: false,
      supportsReasoning: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  'o1-': {
    name: 'o1-',
    fullName: 'o1-mini-2024-09-12',
    openrouterFullName: 'openai/o1-mini-2024-09-12',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 65536,
    contextWindow: 128000,
    inputPrice: 3.0,
    outputPrice: 12.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsAutoPromptCaching: true,
      supportsVision: false,
      supportsReasoning: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },

  // ===== OpenAI Models =====
  gpt4o: {
    name: 'gpt4o',
    fullName: 'gpt-4o-2024-08-06',
    openrouterFullName: 'openai/gpt-4o-2024-08-06',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 16384,
    contextWindow: 128000,
    inputPrice: 2.5,
    outputPrice: 10.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsAutoPromptCaching: true,
      supportsPredictiveOutput: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gpt4t: {
    name: 'gpt4t',
    fullName: 'gpt-4-turbo-2024-04-09',
    openrouterFullName: 'openai/gpt-4-turbo-2024-04-09',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 4096,
    contextWindow: 128000,
    inputPrice: 10.0,
    outputPrice: 30.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsAutoPromptCaching: false,
      supportsReasoning: false,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  'gpt4o-': {
    name: 'gpt4o-',
    fullName: 'gpt-4o-mini-2024-07-18',
    openrouterFullName: 'openai/gpt-4o-mini-2024-07-18',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 16384,
    contextWindow: 128000,
    inputPrice: 0.15,
    outputPrice: 0.6,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsAutoPromptCaching: true,
      supportsPredictiveOutput: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gpt4ol: {
    name: 'gpt4ol',
    fullName: 'chatgpt-4o-latest',
    openrouterFullName: 'openai/chatgpt-4o-latest',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 16384,
    contextWindow: 128000,
    inputPrice: 5.0,
    outputPrice: 15.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsAutoPromptCaching: true,
      supportsReasoning: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },

  // ===== Google Gemini Models =====
  gemini2p: {
    name: 'gemini2p',
    fullName: 'gemini-2.0-pro-exp-02-05',
    openrouterFullName: 'google/gemini-2.0-pro-exp-02-05:free',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 200000,
    contextWindow: 2097152,
    inputPrice: 1.25,
    outputPrice: 5.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsVision: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini2fT: {
    name: 'gemini2fT',
    fullName: 'gemini-2.0-flash-thinking-exp-01-21',
    openrouterFullName: 'google/gemini-2.0-flash-thinking-exp:free',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 200000,
    contextWindow: 1048576,
    inputPrice: 0.075,
    outputPrice: 0.3,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsNativePdf: false,
      supportsVision: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini2f: {
    name: 'gemini2f',
    fullName: 'gemini-2.0-flash-001',
    openrouterFullName: 'google/gemini-2.0-flash-001',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 200000,
    contextWindow: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsNativePdf: true,
      supportsVision: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  'gemini1p+': {
    name: 'gemini1p+',
    fullName: 'gemini-1.5-pro-latest',
    openrouterFullName: 'google/gemini-1.5-pro',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 200000,
    contextWindow: 1048576,
    inputPrice: 1.25,
    outputPrice: 5.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsNativePdf: true,
      supportsVision: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  'gemini1f+': {
    name: 'gemini1f+',
    fullName: 'gemini-1.5-fresh-latest',
    openrouterFullName: 'google/gemini-1.5-fresh',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 100000,
    contextWindow: 1048576,
    inputPrice: 0.075,
    outputPrice: 0.3,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsNativePdf: true,
      supportsVision: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },

  // ===== xAI Models =====
  grok2: {
    name: 'grok2',
    fullName: 'grok-2-1212',
    openrouterFullName: 'grok-ai/grok-2-1212',
    provider: ModelProvider.XAI,
    maxOutputTokens: 131072,
    contextWindow: 131072,
    inputPrice: 2.0,
    outputPrice: 10.0,
    capabilities: DEFAULT_MODEL_CAPABILITIES satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  grok2v: {
    name: 'grok2v',
    fullName: 'grok-2-1212-vision',
    openrouterFullName: 'grok-ai/grok-2-1212-vision',
    provider: ModelProvider.XAI,
    maxOutputTokens: 32768,
    contextWindow: 32768,
    inputPrice: 2.0,
    outputPrice: 10.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsVision: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },

  // ===== OpenRouter Models =====
  'llama3+': {
    name: 'llama3+',
    fullName: 'meta-llama/llama-3.1-405b-instruct',
    openrouterFullName: 'meta-llama/llama-3.1-405b-instruct',
    provider: ModelProvider.OTHERS,
    maxOutputTokens: 131072,
    contextWindow: 131072,
    inputPrice: 3.0,
    outputPrice: 3.0,
    capabilities: DEFAULT_MODEL_CAPABILITIES satisfies ModelCapabilities,
    openRouterOnly: true,
  },
  'qvq-72b': {
    name: 'qvq-72b',
    fullName: 'qwen/qvq-72b-preview',
    openrouterFullName: 'qwen/qvq-72b-preview',
    provider: ModelProvider.OTHERS,
    maxOutputTokens: 4096,
    contextWindow: 128000,
    inputPrice: 0.25,
    outputPrice: 0.5,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
    } satisfies ModelCapabilities,
    openRouterOnly: true,
  },
  DSV3: {
    name: 'DSV3',
    fullName: 'deepseek/deepseek-chat',
    openrouterFullName: 'deepseek/deepseek-chat',
    provider: ModelProvider.OTHERS,
    maxOutputTokens: 66000,
    contextWindow: 131000,
    inputPrice: 0.14,
    outputPrice: 0.28,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      // supportsAssistantPrefill: true,
      // supportsAutoPromptCaching: true,
      // I think both are supported via the official deepseek API, but not exposed in the openrouter API
    } satisfies ModelCapabilities,
    openRouterOnly: true,
  },
  DSR1: {
    name: 'DSR1',
    fullName: 'deepseek/deepseek-R1',
    openrouterFullName: 'deepseek/deepseek-R1',
    provider: ModelProvider.OTHERS,
    maxOutputTokens: 64000,
    contextWindow: 164000,
    inputPrice: 8,
    outputPrice: 8,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      // supportsAssistantPrefill: true,
      // supportsAutoPromptCaching: true,
      // I think both are supported via the official deepseek API, but not exposed in the openrouter API
      supportsReasoning: true,
    } satisfies ModelCapabilities,
    openRouterOnly: true,
  },
};
