/**
 * The icon *name* vocabulary — UI-free.
 *
 * `webAwesomeIcons.ts` pairs each of these names with a Font Awesome icon
 * definition (and imports Lit for the `waIcon` template helper), which pulls
 * ~200 FontAwesome modules plus Lit into the type graph of anything that
 * imports from it — even a bare `import type`. Consumers outside the UI layer
 * (schemas, non-UI shared code) that only need the *name* union or the
 * codicon-alias table should import from here instead.
 *
 * `webAwesomeIcons.ts` builds its `icons` map `satisfies
 * Record<(typeof TEXRA_ICON_CANONICAL_NAMES)[number], FontAwesomeIconDefinition>`
 * against {@link TEXRA_ICON_CANONICAL_NAMES}, so the two lists cannot drift:
 * adding, removing, or renaming a canonical icon without updating the other
 * file is a compile error, not a silent mismatch.
 */

// Canonical Font Awesome names, matching the keys of `icons` in
// `webAwesomeIcons.ts` exactly (and in the same order). Add a new icon there
// first, then mirror its key here — the `satisfies` constraint on `icons`
// turns any mismatch into a type error.
export const TEXRA_ICON_CANONICAL_NAMES = [
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-rotate-left',
  'arrow-up',
  'arrow-up-right-from-square',
  'arrows-rotate',
  'backward-step',
  'ban',
  'bolt',
  'book',
  'bookmark',
  'box',
  'box-archive',
  'brain',
  'building',
  'bullseye',
  'caret-down',
  'chart-line',
  'chart-pie',
  'check',
  'check-double',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'circle',
  'circle-check',
  'circle-dot',
  'circle-exclamation',
  'circle-info',
  'circle-question',
  'circle-stop',
  'circle-user',
  'circle-xmark',
  'clock',
  'clock-rotate-left',
  'cloud',
  'cloud-arrow-down',
  'cloud-arrow-up',
  'code',
  'code-branch',
  'code-compare',
  'code-merge',
  'comment',
  'comments',
  'compass',
  'compress',
  'copy',
  'cube',
  'database',
  'diagram-project',
  'download',
  'ellipsis',
  'eraser',
  'eye',
  'file',
  'file-circle-plus',
  'file-code',
  'file-export',
  'file-lines',
  'file-pdf',
  'fish',
  'flask',
  'floppy-disk',
  'folder',
  'folder-open',
  'folder-tree',
  'forward-step',
  'gear',
  'gem',
  'globe',
  'graduation-cap',
  'hashtag',
  'heart',
  'hexagon',
  'image',
  'key',
  'lightbulb',
  'link',
  'list-check',
  'list-ul',
  'magnifying-glass',
  'magnifying-glass-chart',
  'meteor',
  'microphone',
  'minus',
  'moon',
  'note-sticky',
  'palette',
  'paper-plane',
  'pencil',
  'picture-in-picture',
  'plane',
  'play',
  'plus',
  'plus-minus',
  'reply',
  'right-from-bracket',
  'right-to-bracket',
  'robot',
  'rocket',
  'rotate-right',
  'satellite',
  'screwdriver-wrench',
  'server',
  'shield',
  'spinner',
  'star',
  'terminal',
  'thumbtack',
  'thumbtack-slash',
  'trash',
  'triangle-exclamation',
  'user',
  'users',
  'video',
  'wand-magic-sparkles',
  'window-maximize',
  'wrench',
  'xmark',
] as const;

export type TeXRAIconName = (typeof TEXRA_ICON_CANONICAL_NAMES)[number];
