/**
 * Constructs the full chat-export document as a Lit *server-only*
 * template (from `@lit-labs/ssr`). Server-only templates render to
 * clean HTML without lit-html hydration markers, can include the
 * doctype + `<html>` / `<head>` / `<body>` scaffolding, and only
 * accept attribute bindings (no `.foo=` property bindings).
 *
 * The header is plain HTML — it appears once per document so a custom
 * element wouldn't earn its keep. The message bubbles ARE custom
 * elements so their scoped shadow-DOM styling stays out of the page's
 * global stylesheet.
 *
 * Each message body is pre-rendered to HTML by the caller (markdown-it
 * + KaTeX + hljs run on the extension host, where the libraries
 * already live) and slotted into `<texra-chat-message>` /
 * `<texra-chat-tool-block>` via the `unsafeHTML` directive.
 */
import { html as serverHtml } from '@lit-labs/ssr';
import { ifDefined } from 'lit/directives/if-defined.js';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';

// Side-effecting imports — registers the custom elements so
// `<texra-chat-message>` etc. resolve to a class during SSR.
import './components/ChatMessage';
import './components/ChatToolBlock';

export interface PreparedMessage {
  readonly tag: 'texra-chat-message';
  readonly role: 'user' | 'assistant';
  readonly bodyHtml: string;
}

export interface PreparedToolBlock {
  readonly tag: 'texra-chat-tool-block';
  readonly kind:
    | 'call'
    | 'result'
    | 'web-search'
    | 'web-results'
    | 'web-fetch';
  readonly name?: string;
  readonly bodyHtml: string;
}

export type PreparedNode = PreparedMessage | PreparedToolBlock;

export interface PreparedHeader {
  readonly title: string;
  readonly subtitle?: string;
  readonly rows: ReadonlyArray<[string, string]>;
  readonly instruction?: string;
  readonly files: ReadonlyArray<[string, string]>;
}

export interface ExportDocument {
  readonly title: string;
  readonly assetsHref: string;
  readonly header: PreparedHeader;
  readonly nodes: ReadonlyArray<PreparedNode>;
}

function renderNode(node: PreparedNode) {
  if (node.tag === 'texra-chat-message') {
    return serverHtml`<texra-chat-message data-role=${node.role}>${unsafeHTML(
      node.bodyHtml,
    )}</texra-chat-message>`;
  }
  return serverHtml`<texra-chat-tool-block
    data-kind=${node.kind}
    name=${ifDefined(node.name)}
  >${unsafeHTML(node.bodyHtml)}</texra-chat-tool-block>`;
}

function renderHeader(header: PreparedHeader) {
  return serverHtml`<header class="export-header">
    <h1 class="export-title">${header.title}</h1>
    ${
      header.subtitle
        ? serverHtml`<p class="export-subtitle">${header.subtitle}</p>`
        : ''
    }
    <dl class="meta-grid">
      ${header.rows.map(
        ([label, value]) => serverHtml`<dt>${label}</dt><dd>${value}</dd>`,
      )}
    </dl>
    ${
      header.instruction
        ? serverHtml`<div class="instruction-block"><strong
        >Instruction:</strong> <span>${header.instruction}</span></div>`
        : ''
    }
    ${
      header.files.length
        ? serverHtml`<div class="meta-files"><p class="meta-files-title">Files</p><ul>${header.files.map(
            ([label, value]) =>
              serverHtml`<li>${label}: <code>${value}</code></li>`,
          )}</ul></div>`
        : ''
    }
  </header>`;
}

export function buildExportTemplate(doc: ExportDocument) {
  return serverHtml`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="generator" content="TeXRA chat export" />
  <title>${doc.title}</title>
  <link rel="stylesheet" href="${doc.assetsHref}/katex.min.css" />
  <link rel="stylesheet" href="${doc.assetsHref}/texmath.css" />
  <link
    rel="stylesheet"
    href="${doc.assetsHref}/hljs-light.css"
    media="(prefers-color-scheme: light)"
  />
  <link
    rel="stylesheet"
    href="${doc.assetsHref}/hljs-dark.css"
    media="(prefers-color-scheme: dark)"
  />
  <link rel="stylesheet" href="${doc.assetsHref}/chat.css" />
</head>
<body>
  <main class="page">
    ${renderHeader(doc.header)}
    <div class="conversation">
      ${doc.nodes.map(renderNode)}
    </div>
    <footer class="export-footer">
      Generated by TeXRA — see the original conversation in the TeXRA history pane.
    </footer>
  </main>
</body>
</html>`;
}
