import * as vm from 'node:vm';

import { WorkflowScriptParseError } from './parseScript';

export interface SandboxOptions {
  /** Wall-clock cap for the whole (async) script run. */
  timeoutMs: number;
  filename: string;
}

/**
 * Nondeterminism guards: journal replay assumes a script issues the same
 * agent() calls in the same order every run, so wall-clock and randomness
 * are unavailable (mirror of the constraint documented for hosts: pass
 * timestamps via args, vary prompts by index).
 */
const DETERMINISM_PRELUDE = `
'use strict';
Date.now = () => {
  throw new Error('Date.now() is unavailable in workflow scripts (breaks resume); pass timestamps in via args.');
};
Math.random = () => {
  throw new Error('Math.random() is unavailable in workflow scripts (breaks resume); vary prompts by call index instead.');
};
`;

/**
 * Evaluates a workflow script body in a fresh `node:vm` realm with only the
 * injected primitives (plus the realm's own standard built-ins). Dynamic
 * code generation is disabled and the realm has no `require`/`process`.
 *
 * PROTOTYPE NOTE: `node:vm` is an isolation convenience, not a hardened
 * security boundary. Scripts here are generated by TeXRA's own orchestrator
 * (not arbitrary user input) and the only capabilities reachable are the
 * injected primitives. If scripts ever come from untrusted sources, swap
 * this module for a WASM sandbox (quickjs-emscripten) behind the same
 * signature — callers depend only on `runScriptInSandbox`.
 */
export async function runScriptInSandbox(
  body: string,
  globals: Record<string, unknown>,
  options: SandboxOptions,
): Promise<unknown> {
  const context = vm.createContext(
    { ...globals },
    { codeGeneration: { strings: false, wasm: false } },
  );
  new vm.Script(DETERMINISM_PRELUDE, { filename: 'workflow-prelude.js' }).runInContext(
    context,
  );

  let script: vm.Script;
  try {
    script = new vm.Script(`(async () => {\n${body}\n})()`, {
      filename: options.filename,
    });
  } catch (error) {
    throw new WorkflowScriptParseError(
      `Workflow script syntax error: ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  // The vm-level timeout only bounds the synchronous portion; the overall
  // async run is bounded by the race below.
  const evaluated = script.runInContext(context, {
    timeout: Math.min(options.timeoutMs, 5_000),
  }) as Promise<unknown>;
  return await withTimeout(evaluated, options.timeoutMs, options.filename);
}

async function withTimeout(
  promise: Promise<unknown>,
  timeoutMs: number,
  label: string,
): Promise<unknown> {
  let timer: NodeJS.Timeout | undefined;
  try {
    return await Promise.race([
      promise,
      new Promise<never>((_, reject) => {
        timer = setTimeout(() => {
          reject(
            new Error(`Workflow script ${label} timed out after ${timeoutMs}ms`),
          );
        }, timeoutMs);
      }),
    ]);
  } finally {
    if (timer) clearTimeout(timer);
  }
}
