// Third-party imports
import { LitElement, html, type TemplateResult } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';

// Local imports
import type { StreamTabInfo } from '@shared/schemas';

type StreamStatus =
  | 'running'
  | 'stopped'
  | 'error'
  | 'ready'
  | 'waiting'
  | 'resuming';

interface ToolbarButton {
  id: string;
  icon: string;
  command: string;
  title: string;
  className?: string;
  requiresExecution?: boolean;
  workflowOnly?: boolean;
}

const STATUS_LABELS: Record<string, string> = {
  running: 'Running',
  stopped: 'Stopped',
  error: 'Error',
  ready: 'Ready',
  waiting: 'Waiting for follow-up',
  resuming: 'Resuming',
};

const TOOLBAR_BUTTONS: ToolbarButton[] = [
  {
    id: 'stopStreamBtn',
    icon: 'debug-stop',
    command: 'stopStream',
    title:
      'Request task interruption (current API call will be aborted if supported)',
    className: 'stop-button',
  },
  {
    id: 'runNewBtn',
    icon: 'debug-start',
    command: 'runNew',
    title: 'Start a fresh run (discards previous outputs)',
    className: 'run-button run-new-button',
    workflowOnly: true,
  },
  {
    id: 'resumeBtn',
    icon: 'debug-continue',
    command: 'resume',
    title: 'Resume from saved outputs (continues where it left off)',
    className: 'run-button resume-button toolbar-button--hidden',
    workflowOnly: true,
    requiresExecution: true,
  },
  {
    id: 'restoreStateBtn',
    icon: 'reply',
    command: 'restoreState',
    title: 'Restore this configuration to the main view',
    className: 'restore-button',
  },
  {
    id: 'openTaskStorageBtn',
    icon: 'folder-opened',
    command: 'openTaskStorage',
    title: 'Open the workspace storage folder for this run',
    className: 'storage-button toolbar-button--hidden',
    requiresExecution: true,
  },
  {
    id: 'diffStreamBtn',
    icon: 'diff-multiple',
    command: 'diffStream',
    title: 'Run latexdiff on existing tex files',
    className: 'diff-button',
    workflowOnly: true,
  },
  {
    id: 'cleanStreamBtn',
    icon: 'trash',
    command: 'cleanStream',
    title: 'Clean auxiliary files generated by this run',
    className: 'clean-button',
    workflowOnly: true,
  },
  {
    id: 'packStreamBtn',
    icon: 'archive',
    command: 'packStream',
    title: 'Pack the output for this agent into the History folder',
    className: 'pack-button',
    workflowOnly: true,
  },
];

const ACTIVE_STREAM_BUTTONS = new Set([
  'stopStreamBtn',
  'restoreStateBtn',
  'openTaskStorageBtn',
]);

const IDLE_STREAM_BUTTONS = new Set([
  'runNewBtn',
  'resumeBtn',
  'packStreamBtn',
  'cleanStreamBtn',
  'restoreStateBtn',
  'diffStreamBtn',
  'openTaskStorageBtn',
]);

const READY_STREAM_BUTTONS = new Set([
  'runNewBtn',
  'packStreamBtn',
  'cleanStreamBtn',
  'restoreStateBtn',
  'diffStreamBtn',
  'openTaskStorageBtn',
]);

@customElement('stream-header')
export class StreamHeader extends LitElement {
  @property({ type: Object }) stream: StreamTabInfo | null = null;
  @property({ type: String }) status: StreamStatus = 'ready';
  @property({ type: Boolean }) isWorkflow = false;
  @property({ type: Boolean }) hasExecution = false;
  @property({ type: Object }) runSelectorTemplate?: TemplateResult;

  createRenderRoot(): HTMLElement {
    return this;
  }

  render(): TemplateResult {
    const label = this.stream?.label || this.stream?.name || 'Stream';
    const tooltip = this.stream?.label || this.stream?.name || '';
    const normalizedStatus = this.status || 'ready';

    return html`
      <div class="log-header">
        <div class="log-header__primary">
          <div class="header-left">
            <div class="stream-header">
              <span id="activeStreamName" title=${tooltip}> ${label} </span>
              <span
                class=${classMap({
                  'status-indicator': true,
                  [`is-${normalizedStatus}`]: true,
                })}
                data-status=${STATUS_LABELS[normalizedStatus] ??
                normalizedStatus}
              ></span>
            </div>
            ${this.runSelectorTemplate ?? null}
          </div>
          <div class="header-actions">
            <div id="toolbarContainer">${this.renderButtons()}</div>
          </div>
        </div>
      </div>
    `;
  }

  private renderButtons(): TemplateResult[] {
    const enabledButtons = this.getEnabledButtons();
    return TOOLBAR_BUTTONS.filter(
      (button) => !button.workflowOnly || this.isWorkflow,
    ).map((button) => {
      const requiresExecution = button.requiresExecution ?? false;
      const isExecutionHidden = requiresExecution && !this.hasExecution;
      const isEnabled = enabledButtons.has(button.id) && !isExecutionHidden;

      return html`
        <vscode-toolbar-button
          id=${button.id}
          icon=${button.icon}
          title=${button.title}
          class=${classMap({
            [button.className ?? '']: Boolean(button.className),
            'toolbar-button--hidden': isExecutionHidden,
          })}
          ?disabled=${!isEnabled}
          @click=${() => this.emitCommand(button.command)}
        ></vscode-toolbar-button>
      `;
    });
  }

  private getEnabledButtons(): Set<string> {
    switch (this.status) {
      case 'running':
      case 'waiting':
      case 'resuming':
        return ACTIVE_STREAM_BUTTONS;
      case 'error':
      case 'stopped':
        return IDLE_STREAM_BUTTONS;
      case 'ready':
      default:
        return READY_STREAM_BUTTONS;
    }
  }

  private emitCommand(command: string) {
    if (!this.stream?.name) return;
    this.dispatchEvent(
      new CustomEvent('stream-command', {
        detail: { command, streamId: this.stream.name },
        bubbles: true,
        composed: true,
      }),
    );
  }
}
