import type { DiffStats } from './DiffTypes';

/**
 * Information about an output file generated by an agent round.
 */
export interface OutputFileInfo extends DiffStats {
  /** Full path to the generated file */
  path: string;
  /** Corresponding base file if available */
  base?: string | null;
  /** Corresponding previous round file if available */
  prev?: string | null;
}
