// (none needed)

// Third-party imports
import OpenAI from 'openai';

// Local imports - agent
import { AgentWorkspaceState } from '@agent/core/AgentWorkspaceState';

// Local imports - agent components
import type { ToolDefinition } from '@model';

// Internal imports
import { K_SLICE } from '@utils/config';

// Local file imports
import { ModelHandlerOpenAI } from './modelHandlerOpenAI';
import {
  describeAttachments,
  extractToolAttachments,
} from './utils/toolAttachmentUtils';
import { BaseReasoningStreamAggregator } from './BaseReasoningStreamAggregator';

// Type imports
import type {
  CreateResponseOptions,
  DeepSeekToolCall,
} from './types/IModelHandler';
import type {
  ChatCompletion,
  ChatCompletionAssistantMessageParam,
  ChatCompletionChunk,
  ChatCompletionToolMessageParam,
  ChatCompletionMessageFunctionToolCall,
  ChatCompletionMessageParam,
} from 'openai/resources/chat/completions';

// TODO: prompt_cache_hit_tokens can also be used here to correct the price and response usage computation in the base class (just overwrite the computePrice and computeResponseUsage methods with a revalues responseUsage.prompt_tokens_details?.cached_tokens and then call the super methods)
// DEEPSEEK RESPONSE USAGE FORMAT:
// usage
// object
// Usage statistics for the completion request.
// completion_tokens
// integer
// REQUIRED
// Number of tokens in the generated completion.
// prompt_tokens
// integer
// REQUIRED
// Number of tokens in the prompt. It equals prompt_cache_hit_tokens + prompt_cache_miss_tokens.
// prompt_cache_hit_tokens
// integer
// REQUIRED
// Number of tokens in the prompt that hits the context cache.
// prompt_cache_miss_tokens
// integer
// REQUIRED
// Number of tokens in the prompt that misses the context cache.
// total_tokens
// integer
// REQUIRED
// Total number of tokens used in the request (prompt + completion).
// completion_tokens_details
// object
// Breakdown of tokens used in a completion.
// reasoning_tokens
// integer
// Tokens generated by the model for reasoning.

/**
 * Handler for DeepSeek models using OpenAI-compatible API.
 */
export class ModelHandlerDeepSeek extends ModelHandlerOpenAI<DeepSeekToolCall> {
  protected createStreamingAggregator(): BaseReasoningStreamAggregator | null {
    return new BaseReasoningStreamAggregator();
  }

  /**
   * Process thinking blocks for DeepSeek models
   * @param responseObject The raw response object from the model
   * @param workspaceState Optional workspaceState to update with the thinking block
   * @returns The extracted reasoning_content or null if none
   */
  processThinkingBlock(
    responseObject: any,
    workspaceState?: AgentWorkspaceState,
  ): string | null {
    if (!responseObject) {
      return null;
    }

    // Extract reasoning content from DeepSeek response
    let reasoningContent = null;

    // Check for reasoning_content based on DeepSeek API structure
    // Example from their site: response.choices[0].message.reasoning_content
    if (
      responseObject.choices &&
      responseObject.choices.length > 0 &&
      responseObject.choices[0].message
    ) {
      const message = responseObject.choices[0].message;

      // Primary location according to DeepSeek docs
      if (message.reasoning_content) {
        reasoningContent = message.reasoning_content;
        this.logger.debug(
          'Found reasoning_content in choices[0].message.reasoning_content',
        );

        // If workspaceState is provided and we have reasoning content,
        // store it in the workspaceState for future use (similar to Anthropic thinking blocks)
        if (workspaceState && !workspaceState.reasoning.thinkingAdded) {
          // Create a thinking block in the same format as Anthropic for consistency
          const thinkingBlock = {
            type: 'thinking',
            thinking: reasoningContent,
          };

          workspaceState.reasoning.thinkingBlocks = [thinkingBlock];
          workspaceState.reasoning.thinkingAdded = true;
          // this.logger.debug('Added reasoning content to workspaceState');
        }
        // For deepseek mode thinking content should not be attached back to the message as a content item.
        // Nevertheless one can include one in a bare way...
      }
    }
    if (!reasoningContent) {
      return null;
    }

    // Log preview of thinking content (assuming it's a string)
    this.logger.debug(
      `DeepSeek reasoning content preview: ${reasoningContent.substring(0, K_SLICE)}...`,
    );

    // Return the reasoning content (already a string for DeepSeek)
    return reasoningContent;
  }

  protected override parseArguments(raw: unknown): unknown {
    if (typeof raw !== 'string') {
      return raw;
    }

    try {
      return JSON.parse(raw);
    } catch (error) {
      this.logger.warn(
        'DeepSeek tool call arguments could not be parsed as JSON; using raw string.',
        { data: error },
      );
      return raw;
    }
  }

  extractToolUse(responseObject: ChatCompletion): DeepSeekToolCall[] {
    const toolCalls = responseObject?.choices?.[0]?.message?.tool_calls;
    if (Array.isArray(toolCalls) && toolCalls.length > 0) {
      return toolCalls
        .filter(
          (
            call,
          ): call is ChatCompletionMessageFunctionToolCall & { id: string } =>
            Boolean(
              call &&
                typeof call === 'object' &&
                (call as ChatCompletionMessageFunctionToolCall).function
                  ?.name &&
                call.id,
            ),
        )
        .map((call) => ({
          provider: 'deepseek',
          callId: call.id,
          name: call.function!.name,
          input: this.parseArguments(call.function!.arguments),
          raw: call,
        }));
    }

    return [];
  }

  async createToolUseFollowUpMessages(
    _client: OpenAI | undefined,
    call: DeepSeekToolCall,
    result: Record<string, unknown>,
    _workspaceState?: AgentWorkspaceState,
    text?: string,
  ): Promise<ChatCompletionMessageParam[]> {
    const toolCall = this.normalizeToolCall(call.raw);
    const callMsg: ChatCompletionAssistantMessageParam = {
      role: 'assistant',
      tool_calls: [toolCall],
    };
    if (text) {
      callMsg.content = text;
    }
    const { attachments, sanitizedResult } = extractToolAttachments(result);
    if (attachments.length > 0) {
      (sanitizedResult as Record<string, unknown>).attachmentSummary =
        `Attachments available:\n${describeAttachments(attachments).join(
          '\n',
        )}\nUse the read_file tool to download them.`;
    }
    const resultMsg: ChatCompletionToolMessageParam = {
      role: 'tool',
      tool_call_id: toolCall.id,
      content: JSON.stringify(sanitizedResult),
    };
    return [callMsg, resultMsg];
  }

  /**
   * Override createResponse to preprocess messages for Deepseek models
   */
  async createResponse(
    options: CreateResponseOptions<ChatCompletionMessageParam, OpenAI>,
  ): Promise<ChatCompletion> {
    const { messages } = options;
    // Preprocess messages to merge consecutive messages and convert content to strings
    const processedMessages = this.prepareNormalizedMessages(
      messages,
      {
        mergeConsecutiveRoles: true,
        convertContentToString: true,
      },
      'Deepseek',
    );

    // Call the parent implementation with the processed messages
    return super.createResponse({
      ...options,
      messages: processedMessages,
    });
  }
}
