// Third-party imports
import OpenAI from 'openai';

// Local file imports
import type { AgentWorkspaceState } from '@agent/core/AgentWorkspaceState';
import type { ToolFileAttachment } from '@tools/result';
import { isNonEmptyString } from '@utils/core';
import { ModelHandlerOpenAI } from './modelHandlerOpenAI';
import { BaseReasoningStreamAggregator } from './BaseReasoningStreamAggregator';
import type { NormalizeOpenAIMessageContentOptions } from './openAIMessageUtils';
import type { ToolResultPayload } from './utils/toolAttachmentUtils';

// Type imports
import type { DeepSeekToolCall } from './types/IModelHandler';
import type {
  ChatCompletionMessageParam,
  ChatCompletionAssistantMessageParam,
} from 'openai/resources/chat/completions';

// TODO: prompt_cache_hit_tokens can also be used here to correct the price computation in the base class (just overwrite the computePrice method with revalued responseUsage.prompt_tokens_details?.cached_tokens and then call the super method)
// DEEPSEEK RESPONSE USAGE FORMAT:
// usage
// object
// Usage statistics for the completion request.
// completion_tokens
// integer
// REQUIRED
// Number of tokens in the generated completion.
// prompt_tokens
// integer
// REQUIRED
// Number of tokens in the prompt. It equals prompt_cache_hit_tokens + prompt_cache_miss_tokens.
// prompt_cache_hit_tokens
// integer
// REQUIRED
// Number of tokens in the prompt that hits the context cache.
// prompt_cache_miss_tokens
// integer
// REQUIRED
// Number of tokens in the prompt that misses the context cache.
// total_tokens
// integer
// REQUIRED
// Total number of tokens used in the request (prompt + completion).
// completion_tokens_details
// object
// Breakdown of tokens used in a completion.
// reasoning_tokens
// integer
// Tokens generated by the model for reasoning.

/**
 * Extended assistant message type with DeepSeek's reasoning_content field.
 * This is required for thinking mode with tool calls.
 */
type DeepSeekAssistantMessage = ChatCompletionAssistantMessageParam & {
  reasoning_content?: string;
};

/**
 * Handler for DeepSeek models using OpenAI-compatible API.
 *
 * Supports DeepSeek's thinking mode with tool calls. When thinking mode is enabled:
 * - The model outputs reasoning_content along with tool_calls
 * - The reasoning_content must be included in assistant messages during tool-use cycles
 *
 * Reasoning content lifecycle:
 * - Captured in processThinkingBlock() on each model response
 * - Consumed (and cleared) when creating tool-use follow-up messages
 * - Overwritten on next model response if not consumed (no leak between turns)
 *
 * Note: Handler instances are created per-agent-run, not shared across requests.
 *
 * @see https://api-docs.deepseek.com/guides/thinking_with_tools
 */
export class ModelHandlerDeepSeek extends ModelHandlerOpenAI<DeepSeekToolCall> {
  // toolCallProvider and usageProvider inherit from base class via config.provider

  /**
   * DeepSeek models don't support vision/attachments in tool results.
   */
  override get canProcessToolResultAttachments(): boolean {
    return false;
  }

  /**
   * DeepSeek expects string content format instead of array format.
   */
  protected override formatAssistantContent(text: string): string {
    return text;
  }

  protected createStreamingAggregator(): BaseReasoningStreamAggregator | null {
    return new BaseReasoningStreamAggregator();
  }

  /**
   * Builds an assistant message with tool calls and reasoning_content.
   * Reads reasoning from workspaceState and clears it after use.
   *
   * This follows the same pattern as Anthropic/Google handlers:
   * - processThinkingBlock() stores to workspaceState.reasoning
   * - createToolUseFollowUpMessages() reads and clears via this method
   */
  private buildAssistantMessageWithReasoning(
    toolCalls: ReturnType<typeof this.normalizeToolCall>[],
    workspaceState?: AgentWorkspaceState,
    text?: string,
  ): DeepSeekAssistantMessage {
    const callMsg: DeepSeekAssistantMessage = {
      role: 'assistant',
      tool_calls: toolCalls,
    };

    // Include reasoning_content from workspaceState if available
    const reasoningContent =
      workspaceState?.reasoning.thinkingBlocks[0]?.thinking;
    if (reasoningContent) {
      callMsg.reasoning_content = reasoningContent;
      // Clear after use (same pattern as Anthropic handler)
      workspaceState?.resetReasoning();
    }

    if (text) {
      callMsg.content = this.formatAssistantContent(text);
    }

    return callMsg;
  }

  // processThinkingBlock is inherited from base class - it already stores
  // reasoning to workspaceState.reasoning.thinkingBlocks

  /**
   * Creates tool-use follow-up messages with reasoning_content support.
   *
   * For DeepSeek thinking mode, the assistant message must include
   * reasoning_content when tool calls are made. This allows the model
   * to continue its reasoning chain across tool-use cycles.
   *
   * Follows the same pattern as Anthropic handler:
   * - Reads reasoning from workspaceState.reasoning.thinkingBlocks
   * - Clears reasoning after including it in the message
   *
   * Attachments are ignored since DeepSeek doesn't support them.
   */
  override async createToolUseFollowUpMessages(
    _client: OpenAI | undefined,
    call: DeepSeekToolCall,
    result: ToolResultPayload,
    _attachments: ToolFileAttachment[],
    workspaceState?: AgentWorkspaceState,
    text?: string,
  ): Promise<ChatCompletionMessageParam[]> {
    const toolCall = this.normalizeToolCall(call.raw);
    const callMsg = this.buildAssistantMessageWithReasoning(
      [toolCall],
      workspaceState,
      text,
    );

    // Result is already sanitized by source - attachments are ignored
    // Use plain text instead of JSON (Claude Code pattern) to save tokens
    const resultMsg = {
      role: 'tool' as const,
      tool_call_id: toolCall.id,
      content: this.formatToolResultAsText(result),
    };

    // Type assertion needed: DeepSeekAssistantMessage extends ChatCompletionAssistantMessageParam
    // with reasoning_content field that OpenAI's types don't know about
    return [callMsg as ChatCompletionMessageParam, resultMsg];
  }

  /**
   * Creates batched tool-use follow-up messages for multiple parallel tool calls.
   *
   * For DeepSeek thinking mode, all tool calls from a single model response
   * should be in ONE assistant message with reasoning_content, followed by
   * individual tool result messages.
   *
   * Attachments are ignored since DeepSeek doesn't support them.
   *
   * @param calls - Array of tool calls from the model response
   * @param results - Array of sanitized results (same order as calls)
   * @param _attachmentsPerCall - Array of attachment arrays (ignored for DeepSeek)
   * @param workspaceState - Workspace state containing reasoning blocks
   * @param text - Optional text content to include in the assistant message
   * @throws Error if calls and results arrays have different lengths
   */
  async createBatchedToolUseFollowUpMessages(
    calls: DeepSeekToolCall[],
    results: ToolResultPayload[],
    attachmentsPerCall: ToolFileAttachment[][],
    workspaceState?: AgentWorkspaceState,
    text?: string,
  ): Promise<ChatCompletionMessageParam[]> {
    // Validate input arrays (consistent with Google handler)
    if (calls.length !== results.length) {
      throw new Error(
        `DeepSeek batched tool calls mismatch: ${calls.length} calls vs ${results.length} results`,
      );
    }

    if (calls.length !== attachmentsPerCall.length) {
      throw new Error(
        `DeepSeek batched tool calls mismatch: ${calls.length} calls vs ${attachmentsPerCall.length} attachment arrays`,
      );
    }

    if (calls.length === 0) {
      return [];
    }

    // Build assistant message with ALL tool calls and reasoning_content
    const toolCalls = calls.map((call) => this.normalizeToolCall(call.raw));
    const callMsg = this.buildAssistantMessageWithReasoning(
      toolCalls,
      workspaceState,
      text,
    );

    // Type assertion needed: DeepSeekAssistantMessage extends ChatCompletionAssistantMessageParam
    // with reasoning_content field that OpenAI's types don't know about
    // Build tool result messages - use plain text instead of JSON to save tokens
    const toolResultMessages = toolCalls.map((call, i) => ({
      role: 'tool' as const,
      tool_call_id: call.id,
      content: this.formatToolResultAsText(results[i]),
    }));

    return [callMsg as ChatCompletionMessageParam, ...toolResultMessages];
  }

  /**
   * Format tool result as plain text instead of JSON to save tokens.
   * Follows Claude Code pattern of preferring human-readable output.
   */
  private formatToolResultAsText(result: ToolResultPayload): string {
    const textPieces: string[] = [];
    if (isNonEmptyString(result.output)) {
      textPieces.push(result.output);
    }
    if (result.userInstruction) {
      textPieces.push(`User feedback: ${result.userInstruction}`);
    }
    if (result.isError && !result.output && result.error) {
      textPieces.push(result.error);
    }
    if (textPieces.length === 0 && result.summary) {
      textPieces.push(result.summary);
    }
    return textPieces.join('\n\n') || 'OK';
  }

  /**
   * DeepSeek requires merging consecutive roles and converting content to strings.
   */
  protected override getMessageNormalizationOptions(): NormalizeOpenAIMessageContentOptions {
    return {
      mergeConsecutiveRoles: true,
      convertContentToString: true,
    };
  }
}
