// Standard library imports
// (none needed)

// Third-party imports
import OpenAI from 'openai';
import type {
  ChatCompletionAssistantMessageParam,
  ChatCompletionToolMessageParam,
  ChatCompletionMessageToolCall,
  ChatCompletionMessage,
} from 'openai/resources/chat/completions';

// Local imports - agent
import { ToolState } from '../core/ToolState';

// Local imports - agent components
import { ModelHandlerOpenAI } from './modelHandlerOpenAI';
import { OpenAIStreamDeltaAggregator } from './openAIStreamAggregators';

// Local imports - utilities
import { convertContentToString } from '@agent/utils/text/messageUtils';
import type { ToolDefinition } from '@model';
import { K_SLICE, MESSAGE_PREVIEW_LENGTH } from '@utils/config';

// TODO: prompt_cache_hit_tokens can also be used here to correct the price and response usage computation in the base class (just overwrite the computePrice and computeResponseUsage methods with a revalues responseUsage.prompt_tokens_details?.cached_tokens and then call the super methods)
// DEEPSEEK RESPONSE USAGE FORMAT:
// usage
// object
// Usage statistics for the completion request.
// completion_tokens
// integer
// REQUIRED
// Number of tokens in the generated completion.
// prompt_tokens
// integer
// REQUIRED
// Number of tokens in the prompt. It equals prompt_cache_hit_tokens + prompt_cache_miss_tokens.
// prompt_cache_hit_tokens
// integer
// REQUIRED
// Number of tokens in the prompt that hits the context cache.
// prompt_cache_miss_tokens
// integer
// REQUIRED
// Number of tokens in the prompt that misses the context cache.
// total_tokens
// integer
// REQUIRED
// Total number of tokens used in the request (prompt + completion).
// completion_tokens_details
// object
// Breakdown of tokens used in a completion.
// reasoning_tokens
// integer
// Tokens generated by the model for reasoning.

/**
 * Handler for DeepSeek models using OpenAI-compatible API.
 */
export class ModelHandlerDeepSeek extends ModelHandlerOpenAI {
  protected override getStreamAggregator() {
    return new OpenAIStreamDeltaAggregator();
  }

  /**
   * Process thinking blocks for DeepSeek models
   * @param responseObject The raw response object from the model
   * @param groupId Optional group ID for logging
   * @param toolState Optional toolState to update with the thinking block
   * @returns The extracted reasoning_content or null if none
   */
  processThinkingBlock(
    responseObject: any,
    groupId?: string,
    toolState?: ToolState,
  ): string | null {
    if (!responseObject) {
      return null;
    }

    // Extract reasoning content from DeepSeek response
    let reasoningContent = null;

    // Check for reasoning_content based on DeepSeek API structure
    // Example from their site: response.choices[0].message.reasoning_content
    if (
      responseObject.choices &&
      responseObject.choices.length > 0 &&
      responseObject.choices[0].message
    ) {
      const message = responseObject.choices[0].message;

      // Primary location according to DeepSeek docs
      if (message.reasoning_content) {
        reasoningContent = message.reasoning_content;
        this.logger.debug(
          'Found reasoning_content in choices[0].message.reasoning_content',
          groupId,
        );

        // If toolState is provided and we have reasoning content,
        // store it in the toolState for future use (similar to Anthropic thinking blocks)
        if (toolState && !toolState.thinkingAdded) {
          // Create a thinking block in the same format as Anthropic for consistency
          const thinkingBlock = {
            type: 'thinking',
            thinking: reasoningContent,
          };

          toolState.thinkingBlocks = [thinkingBlock];
          toolState.thinkingAdded = true;
          // this.logger.debug('Added reasoning content to toolState', groupId);
        }
        // For deepseek mode thinking content should not be attached back to the message as a content item.
        // Nevertheless one can include one in a bare way...
      }
    }
    if (!reasoningContent) {
      return null;
    }

    // Log preview of thinking content (assuming it's a string)
    this.logger.debug(
      `DeepSeek reasoning content preview: ${reasoningContent.substring(0, K_SLICE)}...`,
      groupId,
    );

    // Return the reasoning content (already a string for DeepSeek)
    return reasoningContent;
  }

  extractToolUse(responseObject: any): string | null {
    const toolCalls = responseObject?.choices?.[0]?.message?.tool_calls;
    if (Array.isArray(toolCalls) && toolCalls.length > 0) {
      return JSON.stringify(toolCalls[0], null, 2);
    }
    const func = responseObject?.choices?.[0]?.message?.function_call;
    if (func) {
      return JSON.stringify(func, null, 2);
    }
    return null;
  }

  createToolUseFollowUpMessages(
    id: string,
    name: string,
    call: ChatCompletionMessageToolCall | ChatCompletionMessage.FunctionCall,
    result: Record<string, unknown>,
    _toolState?: ToolState,
    text?: string,
  ): [ChatCompletionAssistantMessageParam, ChatCompletionToolMessageParam] {
    const toolCall = this.normalizeToolCall(id, name, call);
    const callMsg: ChatCompletionAssistantMessageParam = {
      role: 'assistant',
      tool_calls: [toolCall],
    };
    if (text) {
      callMsg.content = text;
    }
    const resultMsg: ChatCompletionToolMessageParam = {
      role: 'tool',
      tool_call_id: toolCall.id ?? id,
      content: JSON.stringify(result),
    };
    return [callMsg, resultMsg];
  }

  /**
   * Preprocess messages array to ensure there are no consecutive user or assistant messages
   * and that content is in string format for DeepSeek models
   * @param messages Original messages array
   * @returns Processed messages array with merged consecutive messages and string content
   */
  private preprocessMessages(messages: any[]): any[] {
    if (!messages || messages.length <= 1) {
      return messages;
    }

    // First, handle merging consecutive messages with the same role
    const mergedMessages: any[] = [messages[0]];

    for (let i = 1; i < messages.length; i++) {
      const currentMessage = messages[i];
      const previousMessage = mergedMessages[mergedMessages.length - 1];

      // If current message has the same role as the previous one, merge them
      if (currentMessage.role === previousMessage.role) {
        this.logger.debug(
          `Merging consecutive ${currentMessage.role} messages`,
        );

        // Handle content merging based on content type
        if (
          Array.isArray(previousMessage.content) &&
          Array.isArray(currentMessage.content)
        ) {
          // If both have content arrays, concatenate them
          previousMessage.content.push(...currentMessage.content);
        } else if (Array.isArray(previousMessage.content)) {
          // If previous has content array but current doesn't
          if (typeof currentMessage.content === 'string') {
            previousMessage.content.push({
              type: 'text',
              text: currentMessage.content,
            });
          }
        } else if (Array.isArray(currentMessage.content)) {
          // If current has content array but previous doesn't
          if (typeof previousMessage.content === 'string') {
            const textContent = previousMessage.content;
            previousMessage.content = [
              { type: 'text', text: textContent },
              ...currentMessage.content,
            ];
          }
        } else if (
          typeof previousMessage.content === 'string' &&
          typeof currentMessage.content === 'string'
        ) {
          // If both are strings, concatenate them with a newline
          previousMessage.content =
            previousMessage.content + '\n' + currentMessage.content;
        }
      } else {
        // Different roles, add as a new message
        mergedMessages.push(currentMessage);
      }
    }

    // Now convert all content arrays to strings for DeepSeek compatibility
    const processedMessages = mergedMessages.map((message) => {
      // Clone the message to avoid modifying the original
      const processedMessage = { ...message };

      // Convert content to string if it's an array
      if (Array.isArray(processedMessage.content)) {
        processedMessage.content = convertContentToString(
          processedMessage.content,
        );
        this.logger.debug(
          `Converted content array to string for ${processedMessage.role} message`,
        );
      }

      return processedMessage;
    });

    return processedMessages;
  }

  /**
   * Override createResponse to preprocess messages for Deepseek models
   */
  async createResponse(
    client: OpenAI,
    messages: any[],
    temperature: number,
    systemPrompt?: string,
    endTag?: string,
    signal?: AbortSignal,
    tools?: ToolDefinition[],
  ): Promise<any> {
    // Preprocess messages to merge consecutive messages and convert content to strings
    const processedMessages = this.preprocessMessages(messages);

    if (processedMessages.length !== messages.length) {
      this.logger.info(
        `Preprocessed message array from ${messages.length} to ${processedMessages.length} messages for Deepseek model compatibility`,
      );
    }

    // Log the first few characters of each processed message for debugging
    processedMessages.forEach((msg, index) => {
      const contentPreview =
        typeof msg.content === 'string'
          ? msg.content.substring(0, MESSAGE_PREVIEW_LENGTH)
          : 'non-string content';
      this.logger.debug(`Message ${index} (${msg.role}): ${contentPreview}...`);
    });

    // Call the parent implementation with the processed messages
    return super.createResponse(
      client,
      processedMessages,
      temperature,
      systemPrompt,
      endTag,
      signal,
      tools,
    );
  }
}
