export const PR_POLL_INTERVAL_MS = 30_000;
export const MAX_CONCURRENT_PR_SUBSCRIPTIONS = 25;
export const MAX_CONCURRENT_ISSUE_SUBSCRIPTIONS = 10;
export const MAX_CONCURRENT_REPO_SUBSCRIPTIONS = 3;
