/**
 * Registry of available model configurations.
 */

import {
  ModelConfig,
  ModelProvider,
  ModelCapabilities,
  defaultModelCapabilities,
} from './ModelConfig';

export const MODEL_CONFIGS: Record<string, ModelConfig> = {
  // ===== Anthropic Claude Models =====
  opus: {
    name: 'opus',
    fullName: 'claude-3-opus-20240229',
    openrouterFullName: 'anthropic/claude-3-opus:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 4096,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: {
      ...defaultModelCapabilities,
      supportsPromptCaching: true,
      supportsAssistantPrefill: true,
    },
    useOpenrouter: false,
  },
  'sonnet++': {
    name: 'sonnet++',
    fullName: 'claude-3-5-sonnet-20241022',
    openrouterFullName: 'anthropic/claude-3.5-sonnet:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...defaultModelCapabilities,
      supportsPromptCaching: true,
      supportsAssistantPrefill: true,
      supportsNativePdf: true,
      likesToAskForConfirmation: true,
    },
    useOpenrouter: false,
  },
  'sonnet+': {
    name: 'sonnet+',
    fullName: 'claude-3-5-sonnet-20240620',
    openrouterFullName: 'anthropic/claude-3.5-sonnet-20240620:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...defaultModelCapabilities,
      supportsPromptCaching: true,
      supportsAssistantPrefill: true,
    },
    useOpenrouter: false,
  },
  sonnet: {
    name: 'sonnet',
    fullName: 'claude-3-sonnet-20240229',
    openrouterFullName: 'anthropic/claude-3.5-sonnet-20240229:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...defaultModelCapabilities,
      supportsAssistantPrefill: true,
    },
    useOpenrouter: false,
  },
  'haiku+': {
    name: 'haiku+',
    fullName: 'claude-3-5-haiku-20241022',
    openrouterFullName: 'anthropic/claude-3.5-haiku:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 1.0,
    outputPrice: 5.0,
    capabilities: {
      ...defaultModelCapabilities,
      supportsPromptCaching: true,
      supportsAssistantPrefill: true,
      supportsVision: false,
      likesToAskForConfirmation: true,
    },
    useOpenrouter: false,
  },
  haiku: {
    name: 'haiku',
    fullName: 'claude-3-haiku-20240307',
    openrouterFullName: 'anthropic/claude-3.5-haiku-20240307:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 0.25,
    outputPrice: 1.25,
    capabilities: {
      ...defaultModelCapabilities,
      supportsPromptCaching: true,
      supportsAssistantPrefill: true,
    },
    useOpenrouter: false,
  },

  // ===== OpenAI Reasoning Models =====
  o1: {
    name: 'o1',
    fullName: 'o1-2024-12-17',
    openrouterFullName: 'openai/o1-2024-12-17',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 60.0,
    capabilities: {
      ...defaultModelCapabilities,
      supportsAutoPromptCaching: true,
      supportsVision: true,
      supportsReasoning: true,
    },
    useOpenrouter: false,
  },
  o1preview: {
    name: 'o1preview',
    fullName: 'o1-preview-2024-09-12',
    openrouterFullName: 'openai/o1-preview-2024-09-12',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 32768,
    contextWindow: 128000,
    inputPrice: 15.0,
    outputPrice: 60.0,
    capabilities: {
      ...defaultModelCapabilities,
      supportsAutoPromptCaching: true,
      supportsVision: false,
      supportsReasoning: true,
    },
    useOpenrouter: false,
  },
  'o1-': {
    name: 'o1-',
    fullName: 'o1-mini-2024-09-12',
    openrouterFullName: 'openai/o1-mini-2024-09-12',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 65536,
    contextWindow: 128000,
    inputPrice: 3.0,
    outputPrice: 12.0,
    capabilities: {
      ...defaultModelCapabilities,
      supportsAutoPromptCaching: true,
      supportsVision: false,
      supportsReasoning: true,
    },
    useOpenrouter: false,
  },

  // ===== OpenAI Models =====
  gpt4o: {
    name: 'gpt4o',
    fullName: 'gpt-4o-2024-08-06',
    openrouterFullName: 'openai/gpt-4o-2024-08-06',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 16384,
    contextWindow: 128000,
    inputPrice: 2.5,
    outputPrice: 10.0,
    capabilities: {
      ...defaultModelCapabilities,
      supportsAutoPromptCaching: true,
      supportsPredictiveOutput: true,
    },
    useOpenrouter: false,
  },
  gpt4t: {
    name: 'gpt4t',
    fullName: 'gpt-4-turbo-2024-04-09',
    openrouterFullName: 'openai/gpt-4-turbo-2024-04-09',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 4096,
    contextWindow: 128000,
    inputPrice: 10.0,
    outputPrice: 30.0,
    capabilities: {
      ...defaultModelCapabilities,
      supportsAutoPromptCaching: false,
      supportsReasoning: false,
    },
    useOpenrouter: false,
  },
  'gpt4o-': {
    name: 'gpt4o-',
    fullName: 'gpt-4o-mini-2024-07-18',
    openrouterFullName: 'openai/gpt-4o-mini-2024-07-18',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 16384,
    contextWindow: 128000,
    inputPrice: 0.15,
    outputPrice: 0.6,
    capabilities: {
      ...defaultModelCapabilities,
      supportsAutoPromptCaching: true,
      supportsPredictiveOutput: true,
    },
    useOpenrouter: false,
  },
  gpt4ol: {
    name: 'gpt4ol',
    fullName: 'chatgpt-4o-latest',
    openrouterFullName: 'openai/chatgpt-4o-latest',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 16384,
    contextWindow: 128000,
    inputPrice: 5.0,
    outputPrice: 15.0,
    capabilities: {
      ...defaultModelCapabilities,
      supportsAutoPromptCaching: true,
      supportsReasoning: true,
    },
    useOpenrouter: false,
  },

  // ===== Google Gemini Models =====
  geminiexp: {
    name: 'geminiexp',
    fullName: 'gemini-exp-1206',
    openrouterFullName: 'google/gemini-1.5-pro-exp-0120',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 4096,
    contextWindow: 2097152,
    inputPrice: 1.25,
    outputPrice: 5.0,
    capabilities: {
      ...defaultModelCapabilities,
      supportsVision: true,
    },
    useOpenrouter: false,
  },
  gemini2fthinking: {
    name: 'gemini2fthinking',
    fullName: 'gemini-2.0-flash-thinking-exp-1219',
    openrouterFullName: 'google/gemini-2.0-flash-thinking-exp-1219',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 8192,
    contextWindow: 32768,
    inputPrice: 0.075,
    outputPrice: 0.3,
    capabilities: {
      ...defaultModelCapabilities,
      supportsNativePdf: false,
      supportsVision: true,
    },
    useOpenrouter: false,
  },
  gemini2f: {
    name: 'gemini2f',
    fullName: 'gemini-2.0-flash-exp',
    openrouterFullName: 'google/gemini-2.0-flash-exp',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 8192,
    contextWindow: 1048576,
    inputPrice: 0.075,
    outputPrice: 0.3,
    capabilities: {
      ...defaultModelCapabilities,
      supportsNativePdf: true,
      supportsVision: true,
    },
    useOpenrouter: false,
  },
  'gemini1p+': {
    name: 'gemini1p+',
    fullName: 'gemini-1.5-pro-latest',
    openrouterFullName: 'google/gemini-1.5-pro-latest',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 8192,
    contextWindow: 1048576,
    inputPrice: 1.25,
    outputPrice: 5.0,
    capabilities: {
      ...defaultModelCapabilities,
      supportsNativePdf: true,
      supportsVision: true,
    },
    useOpenrouter: false,
  },
  'gemini1f+': {
    name: 'gemini1f+',
    fullName: 'gemini-1.5-fresh-latest',
    openrouterFullName: 'google/gemini-1.5-fresh-latest',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 8192,
    contextWindow: 1048576,
    inputPrice: 0.075,
    outputPrice: 0.3,
    capabilities: {
      ...defaultModelCapabilities,
      supportsNativePdf: true,
      supportsVision: true,
    },
    useOpenrouter: false,
  },

  // ===== OpenRouter Models =====
  'llama3+': {
    name: 'llama3+',
    fullName: 'meta-llama/llama-3.1-405b-instruct',
    openrouterFullName: 'meta-llama/llama-3.1-405b-instruct',
    provider: ModelProvider.OTHERS,
    maxOutputTokens: 131072,
    contextWindow: 131072,
    inputPrice: 3.0,
    outputPrice: 3.0,
    capabilities: defaultModelCapabilities,
    useOpenrouter: true,
  },
  'qwq-32b': {
    name: 'qwq-32b',
    fullName: 'qwen/qwq-32b-preview',
    openrouterFullName: 'qwen/qwq-32b-preview',
    provider: ModelProvider.OTHERS,
    maxOutputTokens: 32768,
    contextWindow: 32768,
    inputPrice: 0.15,
    outputPrice: 0.6,
    capabilities: {
      ...defaultModelCapabilities,
      supportsReasoning: true,
    },
    useOpenrouter: true,
  },
};
