"""Registry of available model handlers."""

from typing import Dict

from .model_base import ModelProvider, ModelConfig, ModelCapabilities
from .model_anthropic import AnthropicModelConfig
from .model_openai import OpenAIModelConfig, OpenAICompatibleModelConfig


MODEL_HANDLERS: Dict[str, ModelConfig] = {
    # Anthropic Claude models
    "opus": AnthropicModelConfig(
        name="opus",
        full_name="claude-3-opus-20240229",
        max_output_tokens=4096,
        context_window=200000,
        input_price=15.0,
        output_price=75.0,
        capabilities=ModelCapabilities(supports_prompt_caching=True, supports_assistant_prefill=True),
    ),
    "sonnet++": AnthropicModelConfig(
        name="sonnet++",
        full_name="claude-3-5-sonnet-20241022",
        max_output_tokens=8192,
        context_window=200000,
        input_price=3.0,
        output_price=15.0,
        capabilities=ModelCapabilities(
            supports_prompt_caching=True, supports_native_pdf=True, supports_assistant_prefill=True, likes_to_ask_for_confirmation=True
        ),
    ),
    "sonnet+": AnthropicModelConfig(
        name="sonnet+",
        full_name="claude-3-5-sonnet-20240620",
        max_output_tokens=8192,
        context_window=200000,
        input_price=3.0,
        output_price=15.0,
        capabilities=ModelCapabilities(supports_prompt_caching=True, supports_assistant_prefill=True),
    ),
    "sonnet": AnthropicModelConfig(
        name="sonnet",
        full_name="claude-3-sonnet-20240229",
        max_output_tokens=8192,
        context_window=200000,
        input_price=3.0,
        output_price=15.0,
        capabilities=ModelCapabilities(supports_prompt_caching=False, supports_assistant_prefill=True),
    ),
    "haiku+": AnthropicModelConfig(
        name="haiku+",
        full_name="claude-3-5-haiku-20241022",
        max_output_tokens=8192,
        context_window=200000,
        input_price=1.0,
        output_price=5.0,
        capabilities=ModelCapabilities(
            supports_prompt_caching=True, supports_vision=False, supports_assistant_prefill=True, likes_to_ask_for_confirmation=True
        ),
    ),
    "haiku": AnthropicModelConfig(
        name="haiku",
        full_name="claude-3-haiku-20240307",
        max_output_tokens=8192,
        context_window=200000,
        input_price=0.25,
        output_price=1.25,
        capabilities=ModelCapabilities(supports_prompt_caching=True, supports_assistant_prefill=True),
    ),
    # OpenAI models
    "gpto1": OpenAIModelConfig(
        name="gpto1",
        full_name="o1-preview-2024-09-12",
        max_output_tokens=32768,
        context_window=128000,
        input_price=15.0,
        output_price=60.0,
        capabilities=ModelCapabilities(supports_auto_prompt_caching=True, supports_vision=False, supports_reasoning=True),
    ),
    "gpto1-": OpenAIModelConfig(
        name="gpto1-",
        full_name="o1-mini-2024-09-12",
        max_output_tokens=65536,
        context_window=128000,
        input_price=3.0,
        output_price=12.0,
        capabilities=ModelCapabilities(supports_prompt_caching=True, supports_vision=False, supports_reasoning=True),
    ),
    "gpt4o": OpenAIModelConfig(
        name="gpt4o",
        # full_name="gpt-4o-2024-08-06",
        # gpt-4o,
        full_name="gpt-4o-2024-11-20",
        max_output_tokens=16384,
        context_window=128000,
        input_price=2.5,
        output_price=10.0,
        capabilities=ModelCapabilities(supports_auto_prompt_caching=True, supports_predictive_output=True),
    ),
    "gpt4t": OpenAIModelConfig(
        name="gpt4t",
        full_name="gpt-4-turbo-2024-04-09",
        max_output_tokens=4096,
        context_window=128000,
        input_price=10.0,
        output_price=30.0,
        capabilities=ModelCapabilities(supports_auto_prompt_caching=True, supports_reasoning=True),
    ),
    "gpt4o-": OpenAIModelConfig(
        name="gpt4o-",
        full_name="gpt-4o-mini-2024-07-18",
        max_output_tokens=16384,
        context_window=128000,
        input_price=0.15,
        output_price=0.6,
        capabilities=ModelCapabilities(supports_auto_prompt_caching=True, supports_predictive_output=True),
    ),
    "gpt4ol": OpenAIModelConfig(
        name="gpt4ol",
        full_name="chatgpt-4o-latest",
        max_output_tokens=16384,
        context_window=128000,
        input_price=5.0,
        output_price=15.0,
        capabilities=ModelCapabilities(supports_auto_prompt_caching=True, supports_reasoning=True),
    ),
    "geminiexp": OpenAICompatibleModelConfig(
        name="geminiexp",
        full_name="gemini-exp-1206",
        provider=ModelProvider.GOOGLE,
        max_output_tokens=4096,
        context_window=2097152,
        input_price=1.25,
        output_price=5.0,
        capabilities=ModelCapabilities(supports_prompt_caching=True, supports_assistant_prefill=True),
    ),
    # Google Gemini models
    "gemini2f": OpenAICompatibleModelConfig(
        name="gemini2f",
        full_name="gemini-2.0-flash-exp",
        provider=ModelProvider.GOOGLE,
        max_output_tokens=8192,
        context_window=1048576,
        input_price=0.075,
        output_price=0.3,
        capabilities=ModelCapabilities(supports_prompt_caching=False, supports_native_pdf=True),
    ),
    "gemini1p+": OpenAICompatibleModelConfig(
        name="gemini1p+",
        full_name="gemini-1.5-pro-latest",
        provider=ModelProvider.GOOGLE,
        max_output_tokens=8192,
        input_price=1.25,
        output_price=5.0,
        capabilities=ModelCapabilities(supports_prompt_caching=True, supports_assistant_prefill=True),
    ),
    "gemini1f+": OpenAICompatibleModelConfig(
        name="gemini1f+",
        full_name="gemini-1.5-fresh-latest",
        provider=ModelProvider.GOOGLE,
        max_output_tokens=8192,
        context_window=1048576,
        input_price=0.075,
        output_price=0.3,
        capabilities=ModelCapabilities(supports_prompt_caching=True, supports_native_pdf=True),
    ),
    # OpenRouter models
    "gpt4oOR": OpenAICompatibleModelConfig(
        name="gpt4oOR",
        full_name="openai/gpt-4o:extended",
        provider=ModelProvider.OPENROUTER,
        max_output_tokens=64000,
        context_window=128000,
        input_price=6.0,
        output_price=18.0,
        capabilities=ModelCapabilities(supports_prompt_caching=True, supports_reasoning=True),
    ),
    "gemini1p+OR": OpenAICompatibleModelConfig(
        name="gemini1p+OR",
        full_name="google/gemini-pro-1.5",
        provider=ModelProvider.OPENROUTER,
        max_output_tokens=8192,
        context_window=2097152,
        input_price=2.5,
        output_price=7.5,
        capabilities=ModelCapabilities(supports_prompt_caching=True, supports_assistant_prefill=True),
    ),
    "gemini1f+OR": OpenAICompatibleModelConfig(
        name="gemini1f+OR",
        full_name="google/gemini-flash-1.5",
        provider=ModelProvider.OPENROUTER,
        max_output_tokens=8192,
        context_window=1048576,
        input_price=0.075,
        output_price=0.3,
        capabilities=ModelCapabilities(supports_prompt_caching=True, supports_native_pdf=True),
    ),
    "llama3+OR": OpenAICompatibleModelConfig(
        name="llama3+OR",
        full_name="meta-llama/llama-3.1-405b-instruct",
        provider=ModelProvider.OPENROUTER,
        max_output_tokens=131072,
        context_window=131072,
        input_price=3.0,
        output_price=3.0,
        capabilities=ModelCapabilities(supports_prompt_caching=True, supports_reasoning=True),
    ),
    "qwq-32bOR": OpenAICompatibleModelConfig(
        name="qwq-32b",
        full_name="qwen/qwq-32b-preview",
        provider=ModelProvider.OPENROUTER,
        max_output_tokens=32768,
        context_window=32768,
        input_price=0.15,
        output_price=0.6,
        capabilities=ModelCapabilities(supports_prompt_caching=True, supports_reasoning=True),
    ),
    "sonnet++OR": OpenAICompatibleModelConfig(
        name="sonnet++OR",
        full_name="anthropic/claude-3.5-sonnet:beta",
        provider=ModelProvider.OPENROUTER,
        max_output_tokens=8192,
        context_window=200000,
        input_price=3.0,
        output_price=15.0,
        capabilities=ModelCapabilities(supports_prompt_caching=True, supports_reasoning=True),
    ),
}
