// Supabase "Before User Created" Auth Hook.
//
// Fires synchronously from gotrue before each new auth.users row is inserted —
// for OAuth, email/password, magic link, anonymous, all of it. Returns
// `{error: {http_code, message}}` to block the signup, `{}` to allow.
//
// Wiring: Dashboard → Authentication → Hooks → "Before User Created" →
//   HTTPS hook URL = https://remote.texra.ai/functions/v1/before-user-created
//   Secret        = generated by dashboard, stored as project secret
//                   BEFORE_USER_CREATED_HOOK_SECRET (format "v1,whsec_<base64>").
//
// Payload contract: https://supabase.com/docs/guides/auth/auth-hooks/before-user-created-hook
// Signature contract: Standard Webhooks — https://www.standardwebhooks.com/
// (verified via the reference `standardwebhooks` library, which also enforces
// the spec's timestamp tolerance against replay).

// Local imports
import {
  checkEmailDomain,
  checkGitHubAccountAge,
} from '../_shared/emailPolicy.ts';
import { createWebhookVerifier } from './webhookVerification.ts';

const webhook = createWebhookVerifier(
  Deno.env.get('BEFORE_USER_CREATED_HOOK_SECRET'),
);

const GITHUB_FETCH_TIMEOUT_MS = 3000;

interface HookUser {
  id?: string;
  email?: string;
  app_metadata?: { provider?: string; providers?: string[] };
  user_metadata?: Record<string, unknown>;
}

interface HookRequest {
  metadata?: { uuid?: string; name?: string };
  user?: HookUser;
}

function warn(message: string): void {
  console.warn(`[before-user-created] ${message}`);
}

function allow(): Response {
  return new Response('{}', {
    status: 200,
    headers: { 'content-type': 'application/json' },
  });
}

function block(message: string, httpCode = 400): Response {
  return new Response(
    JSON.stringify({ error: { http_code: httpCode, message } }),
    { status: httpCode, headers: { 'content-type': 'application/json' } },
  );
}

async function fetchGitHubCreatedAt(login: string): Promise<string | null> {
  try {
    const resp = await fetch(
      `https://api.github.com/users/${encodeURIComponent(login)}`,
      {
        headers: {
          Accept: 'application/vnd.github+json',
          'User-Agent': 'TeXRA-AuthHook',
        },
        signal: AbortSignal.timeout(GITHUB_FETCH_TIMEOUT_MS),
      },
    );
    if (!resp.ok) {
      warn(`GitHub /users/${login} returned ${resp.status}`);
      return null;
    }
    const data = await resp.json();
    return typeof data?.created_at === 'string' ? data.created_at : null;
  } catch (e) {
    warn(
      `GitHub fetch failed for ${login}: ${e instanceof Error ? e.message : String(e)}`,
    );
    return null;
  }
}

function extractGitHubLogin(
  meta: Record<string, unknown> | undefined,
): string | null {
  const candidates = [meta?.user_name, meta?.preferred_username];
  return (
    candidates.find(
      (value): value is string => typeof value === 'string' && value.length > 0,
    ) ?? null
  );
}

Deno.serve(async (req) => {
  if (req.method !== 'POST') {
    return new Response('Method not allowed', { status: 405 });
  }

  const rawBody = await req.text();

  let payload: HookRequest;
  try {
    payload = JSON.parse(rawBody) as HookRequest;
  } catch {
    return new Response('Invalid JSON', { status: 400 });
  }

  try {
    // verify() enforces the spec's timestamp tolerance (anti-replay) and
    // validates the signed raw body. JSON was already parsed above so
    // malformed payloads remain 400 rather than looking like auth failures.
    webhook.verify(rawBody, {
      'webhook-id': req.headers.get('webhook-id') ?? '',
      'webhook-timestamp': req.headers.get('webhook-timestamp') ?? '',
      'webhook-signature': req.headers.get('webhook-signature') ?? '',
    });
  } catch {
    warn('Signature verification failed');
    return new Response('Unauthorized', { status: 401 });
  }

  const user = payload.user;
  if (!user?.email) {
    // Nothing to check (e.g. anonymous signups). Don't reject — fail-open.
    return allow();
  }

  const emailDecision = checkEmailDomain(user.email);
  if (!emailDecision.allowed) {
    warn(`Rejected ${user.email}: ${emailDecision.reason}`);
    return block(emailDecision.userMessage);
  }

  if (user.app_metadata?.provider === 'github') {
    const login = extractGitHubLogin(user.user_metadata);
    if (login) {
      const createdAt = await fetchGitHubCreatedAt(login);
      if (createdAt) {
        const ageDecision = checkGitHubAccountAge(createdAt);
        if (!ageDecision.allowed) {
          warn(`Rejected ${user.email} (gh=${login}): ${ageDecision.reason}`);
          return block(ageDecision.userMessage);
        }
      } else {
        // GitHub unavailable / rate-limited / 404. Fail-open rather than
        // block real signups when the network is the problem.
        warn(`Could not fetch GitHub created_at for ${login}; allowing`);
      }
    } else {
      warn(
        `GitHub OAuth but no user_name in metadata for ${user.email}; allowing`,
      );
    }
  }

  return allow();
});
