// Supabase "Before User Created" Auth Hook.
//
// Fires synchronously from gotrue before each new auth.users row is inserted —
// for OAuth, email/password, magic link, anonymous, all of it. Returns
// `{error: {http_code, message}}` to block the signup, `{}` to allow.
//
// Wiring: Dashboard → Authentication → Hooks → "Before User Created" →
//   HTTPS hook URL = https://remote.texra.ai/functions/v1/before-user-created
//   Secret        = generated by dashboard, stored as project secret
//                   BEFORE_USER_CREATED_HOOK_SECRET (format "v1,whsec_<base64>").
//
// Payload contract: https://supabase.com/docs/guides/auth/auth-hooks/before-user-created-hook
// Signature contract: Standard Webhooks — https://www.standardwebhooks.com/

import {
  checkEmailDomain,
  checkGitHubAccountAge,
} from '../_shared/emailPolicy.ts';

const HOOK_SECRET_RAW = Deno.env.get('BEFORE_USER_CREATED_HOOK_SECRET') ?? '';
// Supabase stores the secret as "v1,whsec_<base64>"; strip the prefix.
const HOOK_SECRET_BASE64 = HOOK_SECRET_RAW.replace(/^v1,whsec_/, '');

const GITHUB_FETCH_TIMEOUT_MS = 3000;

interface HookUser {
  id?: string;
  email?: string;
  app_metadata?: { provider?: string; providers?: string[] };
  user_metadata?: Record<string, unknown>;
}

interface HookRequest {
  metadata?: { uuid?: string; name?: string };
  user?: HookUser;
}

function allow(): Response {
  return new Response('{}', {
    status: 200,
    headers: { 'content-type': 'application/json' },
  });
}

function block(message: string, httpCode = 400): Response {
  return new Response(
    JSON.stringify({ error: { http_code: httpCode, message } }),
    { status: httpCode, headers: { 'content-type': 'application/json' } },
  );
}

function decodeBase64(s: string): ArrayBuffer {
  // Return ArrayBuffer (not Uint8Array) so it satisfies WebCrypto's BufferSource
  // under Deno's strict types (Uint8Array<ArrayBufferLike> doesn't match).
  const decoded = atob(s);
  const buf = new ArrayBuffer(decoded.length);
  const view = new Uint8Array(buf);
  for (let i = 0; i < decoded.length; i++) view[i] = decoded.charCodeAt(i);
  return buf;
}

async function verifySignature(
  msgId: string,
  timestamp: string,
  body: string,
  signatureHeader: string,
): Promise<boolean> {
  if (!HOOK_SECRET_BASE64) {
    console.warn(
      '[before-user-created] BEFORE_USER_CREATED_HOOK_SECRET is not set; ' +
        'allowing unsigned requests. Configure the hook secret to enforce verification.',
    );
    return true;
  }

  if (!msgId || !timestamp || !signatureHeader) return false;

  const signedContent = `${msgId}.${timestamp}.${body}`;
  const key = await crypto.subtle.importKey(
    'raw',
    decodeBase64(HOOK_SECRET_BASE64),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['verify'],
  );

  // webhook-signature is space-delimited "v1,<base64> v1,<base64>" (key rotation).
  const candidates = signatureHeader
    .split(' ')
    .filter((s) => s.startsWith('v1,'))
    .map((s) => s.slice(3));

  const msgBytes = new TextEncoder().encode(signedContent);
  for (const sigB64 of candidates) {
    try {
      const ok = await crypto.subtle.verify(
        'HMAC',
        key,
        decodeBase64(sigB64),
        msgBytes,
      );
      if (ok) return true;
    } catch {
      // ignore and try the next candidate
    }
  }
  return false;
}

async function fetchGitHubCreatedAt(login: string): Promise<string | null> {
  try {
    const resp = await fetch(
      `https://api.github.com/users/${encodeURIComponent(login)}`,
      {
        headers: {
          Accept: 'application/vnd.github+json',
          'User-Agent': 'TeXRA-AuthHook',
        },
        signal: AbortSignal.timeout(GITHUB_FETCH_TIMEOUT_MS),
      },
    );
    if (!resp.ok) {
      console.warn(
        `[before-user-created] GitHub /users/${login} returned ${resp.status}`,
      );
      return null;
    }
    const data = await resp.json();
    return typeof data?.created_at === 'string' ? data.created_at : null;
  } catch (e) {
    console.warn(
      `[before-user-created] GitHub fetch failed for ${login}: ${e instanceof Error ? e.message : String(e)}`,
    );
    return null;
  }
}

function extractGitHubLogin(
  meta: Record<string, unknown> | undefined,
): string | null {
  if (!meta) return null;
  const candidates = [meta.user_name, meta.preferred_username];
  for (const c of candidates) {
    if (typeof c === 'string' && c.length > 0) return c;
  }
  return null;
}

Deno.serve(async (req) => {
  if (req.method !== 'POST') {
    return new Response('Method not allowed', { status: 405 });
  }

  const rawBody = await req.text();
  const sigOk = await verifySignature(
    req.headers.get('webhook-id') ?? '',
    req.headers.get('webhook-timestamp') ?? '',
    rawBody,
    req.headers.get('webhook-signature') ?? '',
  );
  if (!sigOk) {
    console.warn('[before-user-created] Signature verification failed');
    return new Response('Unauthorized', { status: 401 });
  }

  let payload: HookRequest;
  try {
    payload = JSON.parse(rawBody) as HookRequest;
  } catch {
    return new Response('Invalid JSON', { status: 400 });
  }

  const user = payload.user;
  if (!user?.email) {
    // Nothing to check (e.g. anonymous signups). Don't reject — fail-open.
    return allow();
  }

  const emailDecision = checkEmailDomain(user.email);
  if (!emailDecision.allowed) {
    console.warn(
      `[before-user-created] Rejected ${user.email}: ${emailDecision.reason}`,
    );
    return block(emailDecision.userMessage);
  }

  if (user.app_metadata?.provider === 'github') {
    const login = extractGitHubLogin(user.user_metadata);
    if (login) {
      const createdAt = await fetchGitHubCreatedAt(login);
      if (createdAt) {
        const ageDecision = checkGitHubAccountAge(createdAt);
        if (!ageDecision.allowed) {
          console.warn(
            `[before-user-created] Rejected ${user.email} (gh=${login}): ${ageDecision.reason}`,
          );
          return block(ageDecision.userMessage);
        }
      } else {
        // GitHub unavailable / rate-limited / 404. Fail-open rather than
        // block real signups when the network is the problem.
        console.warn(
          `[before-user-created] Could not fetch GitHub created_at for ${login}; allowing`,
        );
      }
    } else {
      console.warn(
        `[before-user-created] GitHub OAuth but no user_name in metadata for ${user.email}; allowing`,
      );
    }
  }

  return allow();
});
