// Local imports - webview commands
import { PROGRESS_VIEW_COMMANDS } from '@common/webview/commands';

export const GROUP_DOM_IDS = Object.freeze({
  DETAILS_PREFIX: 'group-',
  HEADER_PREFIX: 'group-header-',
  CONTENT_PREFIX: 'group-content-',
});

export interface ToolbarButtonDefinition {
  id: string;
  icon: string;
  command: string;
  title: string;
  className: string;
  disabled: boolean;
  dataset?: Record<string, string>;
}

const STOP_STREAM_BUTTON: ToolbarButtonDefinition = {
  id: 'stopStreamBtn',
  icon: 'debug-stop',
  command: PROGRESS_VIEW_COMMANDS.STOP_STREAM,
  title:
    'Request task interruption (current API call will be aborted if supported)',
  className: 'stop-button',
  disabled: true,
};

const RESTORE_STATE_BUTTON: ToolbarButtonDefinition = {
  id: 'restoreStateBtn',
  icon: 'reply',
  command: PROGRESS_VIEW_COMMANDS.RESTORE_STATE,
  title: 'Restore this configuration to the main view',
  className: 'restore-button',
  disabled: true,
};

const OPEN_TASK_STORAGE_BUTTON: ToolbarButtonDefinition = {
  id: 'openTaskStorageBtn',
  icon: 'folder-opened',
  command: PROGRESS_VIEW_COMMANDS.OPEN_TASK_STORAGE,
  title: 'Open the workspace storage folder for this run',
  className: 'storage-button toolbar-button--hidden',
  disabled: true,
};

const WORKFLOW_TOOLBAR: ToolbarButtonDefinition[] = [
  STOP_STREAM_BUTTON,
  {
    id: 'runNewBtn',
    icon: 'debug-start',
    command: PROGRESS_VIEW_COMMANDS.RUN_NEW,
    title: 'Start a fresh run (discards previous outputs)',
    className: 'run-button run-new-button',
    disabled: true,
  },
  {
    id: 'resumeBtn',
    icon: 'debug-continue',
    command: PROGRESS_VIEW_COMMANDS.RESUME,
    title: 'Resume from saved outputs (continues where it left off)',
    className: 'run-button resume-button toolbar-button--hidden',
    disabled: true,
  },
  RESTORE_STATE_BUTTON,
  { ...OPEN_TASK_STORAGE_BUTTON },
  {
    id: 'diffStreamBtn',
    icon: 'diff-multiple',
    command: PROGRESS_VIEW_COMMANDS.DIFF_STREAM,
    title: 'Run latexdiff on existing tex files',
    className: 'diff-button',
    disabled: true,
  },
  {
    id: 'cleanStreamBtn',
    icon: 'trash',
    command: PROGRESS_VIEW_COMMANDS.CLEAN_STREAM,
    title: 'Clean auxiliary files generated by this run',
    className: 'clean-button',
    disabled: true,
  },
  {
    id: 'packStreamBtn',
    icon: 'archive',
    command: PROGRESS_VIEW_COMMANDS.PACK_STREAM,
    title: 'Pack the output for this agent into the History folder',
    className: 'pack-button',
    disabled: true,
  },
];

const TOOL_USE_TOOLBAR: ToolbarButtonDefinition[] = [
  STOP_STREAM_BUTTON,
  RESTORE_STATE_BUTTON,
  { ...OPEN_TASK_STORAGE_BUTTON },
];

export const TOOLBAR_BUTTONS: Record<
  'workflow' | 'toolUse',
  ToolbarButtonDefinition[]
> = {
  workflow: WORKFLOW_TOOLBAR,
  toolUse: TOOL_USE_TOOLBAR,
};

export const SORT_BUTTONS = [
  {
    id: 'sortTimeBtn',
    icon: 'clock',
    sort: 'time',
    title: 'Sort by time',
  },
  {
    id: 'sortFileBtn',
    icon: 'file',
    sort: 'inputFile',
    title: 'Sort by file',
  },
  {
    id: 'sortAgentBtn',
    icon: 'account',
    sort: 'agent',
    title: 'Sort by agent',
  },
];

export const FILTER_BUTTONS = [
  {
    id: 'filterAllBtn',
    label: 'All',
    filter: 'all',
  },
  {
    id: 'filterWorkflowBtn',
    label: 'Workflow',
    filter: 'workflow',
  },
  {
    id: 'filterToolBtn',
    label: 'Tool Use',
    filter: 'toolUse',
  },
];
