import {
  DEFAULT_MODEL_CAPABILITIES,
  ModelCapabilities,
  ModelConfig,
  ModelProvider,
  ReasoningEffort,
} from '../ModelConfig';

export const ANTHROPIC_MODELS: Record<string, ModelConfig> = {
  sonnet37T: {
    name: 'sonnet37T',
    fullName: 'claude-3-7-sonnet-20250219',
    openrouterFullName: 'anthropic/claude-3.7-sonnet:thinking',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 21333, // Using extended output with beta header; if >21333, then we need streaming
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      cacheDiscountFactor: 0.1,
      supportsAssistantPrefill: false,
      supportsNativePdf: true,
      supportsReasoning: true,
      supportsTokenCounting: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  sonnet37: {
    name: 'sonnet37',
    fullName: 'claude-3-7-sonnet-20250219',
    openrouterFullName: 'anthropic/claude-3.7-sonnet',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 21333, // Using extended output with beta header; if >21333, then we need streaming
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      cacheDiscountFactor: 0.1,
      supportsAssistantPrefill: true,
      supportsNativePdf: true,
      supportsReasoning: false,
      supportsTokenCounting: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  opus: {
    name: 'opus',
    fullName: 'claude-3-opus-20240229',
    openrouterFullName: 'anthropic/claude-3-opus:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 4096,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      cacheDiscountFactor: 0.1,
      supportsAssistantPrefill: true,
      supportsTokenCounting: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  sonnet36: {
    name: 'sonnet36',
    fullName: 'claude-3-5-sonnet-20241022',
    openrouterFullName: 'anthropic/claude-3.5-sonnet:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      cacheDiscountFactor: 0.1,
      supportsAssistantPrefill: true,
      supportsNativePdf: true,
      supportsTokenCounting: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  sonnet35: {
    name: 'sonnet35',
    fullName: 'claude-3-5-sonnet-20240620',
    openrouterFullName: 'anthropic/claude-3.5-sonnet-20240620:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      cacheDiscountFactor: 0.1,
      supportsAssistantPrefill: true,
      supportsTokenCounting: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  sonnet: {
    name: 'sonnet',
    fullName: 'claude-3-sonnet-20240229',
    openrouterFullName: 'anthropic/claude-3.5-sonnet-20240229:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      cacheDiscountFactor: 0.1,
      supportsAssistantPrefill: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  haiku35: {
    name: 'haiku35',
    fullName: 'claude-3-5-haiku-20241022',
    openrouterFullName: 'anthropic/claude-3.5-haiku:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 1.0,
    outputPrice: 5.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      cacheDiscountFactor: 0.1,
      supportsAssistantPrefill: true,
      supportsVision: true,
      supportsTokenCounting: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  haiku: {
    name: 'haiku',
    fullName: 'claude-3-haiku-20240307',
    openrouterFullName: 'anthropic/claude-3.5-haiku-20240307:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 0.25,
    outputPrice: 1.25,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      cacheDiscountFactor: 0.1,
      supportsAssistantPrefill: true,
      supportsTokenCounting: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
};
