import {
  DEFAULT_MODEL_CAPABILITIES,
  ModelCapabilities,
  ModelConfig,
  ModelProvider,
  ReasoningEffort,
} from '../ModelConfig';

export const GOOGLE_MODELS: Record<string, ModelConfig> = {
  gemini25p: {
    name: 'gemini25p',
    fullName: 'gemini-2.5-pro-preview-05-06',
    openrouterFullName: 'google/gemini-2.5-pro-preview',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 64000,
    contextWindow: 1000000,
    inputPrice: 1.25,
    outputPrice: 10.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      cacheDiscountFactor: 0.25,
      supportsNativePdf: true,
      supportsVision: true,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsNativeAudio: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini25p0325: {
    name: 'gemini25p',
    fullName: 'gemini-2.5-pro-exp-03-25',
    openrouterFullName: 'google/gemini-2.5-pro-exp-03-25:free',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 64000,
    contextWindow: 1000000,
    inputPrice: 1.25,
    outputPrice: 10.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      cacheDiscountFactor: 0.25,
      supportsNativePdf: true,
      supportsVision: true,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsNativeAudio: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini2p: {
    name: 'gemini2p',
    fullName: 'gemini-2.0-pro-exp-02-05',
    openrouterFullName: 'google/gemini-2.0-pro-exp-02-05:free',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 8192,
    contextWindow: 2097152,
    inputPrice: 1.25,
    outputPrice: 5.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      cacheDiscountFactor: 0.25,
      supportsNativePdf: true,
      supportsVision: true,
      supportsNativeAudio: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini25f: {
    name: 'gemini25f',
    fullName: 'gemini-2.5-flash-preview-04-17',
    openrouterFullName: 'google/gemini-2.5-flash-preview-04-17:thinking',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 64000,
    contextWindow: 1000000,
    inputPrice: 1.25,
    outputPrice: 5.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      cacheDiscountFactor: 0.25,
      supportsNativePdf: true,
      supportsVision: true,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsNativeAudio: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini2fT: {
    name: 'gemini2fT',
    fullName: 'gemini-2.0-flash-thinking-exp-01-21',
    openrouterFullName: 'google/gemini-2.0-flash-thinking-exp:free',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 0.075,
    outputPrice: 0.3,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      cacheDiscountFactor: 0.25,
      supportsNativePdf: true,
      supportsVision: true,
      supportsNativeAudio: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini2f: {
    name: 'gemini2f',
    fullName: 'gemini-2.0-flash-001',
    openrouterFullName: 'google/gemini-2.0-flash-001',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 8192,
    contextWindow: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      supportsPromptCaching: true,
      cacheDiscountFactor: 0.25,
      supportsNativePdf: true,
      supportsVision: true,
      supportsNativeAudio: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini15p: {
    name: 'gemini15p',
    fullName: 'gemini-1.5-pro-latest',
    openrouterFullName: 'google/gemini-1.5-pro',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 8192,
    contextWindow: 1048576,
    inputPrice: 1.25,
    outputPrice: 5.0,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      cacheDiscountFactor: 0.25,
      supportsNativePdf: true,
      supportsVision: true,
      supportsNativeAudio: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini15f: {
    name: 'gemini15f',
    fullName: 'gemini-1.5-fresh-latest',
    openrouterFullName: 'google/gemini-1.5-fresh',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 8192,
    contextWindow: 1048576,
    inputPrice: 0.075,
    outputPrice: 0.3,
    capabilities: {
      ...DEFAULT_MODEL_CAPABILITIES,
      cacheDiscountFactor: 0.25,
      supportsNativePdf: true,
      supportsVision: true,
      supportsNativeAudio: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
};
