// Local imports
import {
  DEFAULT_MODEL_CAPABILITIES,
  ModelCapabilities,
  ModelConfig,
  ModelProvider,
  ReasoningEffort,
} from '../ModelConfig';

// Common capabilities for Google models
// Continuation: ModelHandlerGoogle inspects Google's FinishReason stop signals.
// When MAX_TOKENS triggers without emitting the closing tag we enqueue a follow-up
// request so tuning changes should preserve the native stop reasons returned by the API.
const GOOGLE_DEFAULT_CAPABILITIES: ModelCapabilities = {
  ...DEFAULT_MODEL_CAPABILITIES,
  cacheDiscountFactor: 0.25,
  supportsNativePdf: true,
  supportsVision: true,
  supportsNativeAudio: true,
  supportsNativeMCPServer: false, // Google doesn't have native MCP support
};

export const GOOGLE_MODELS: Record<string, ModelConfig> = {
  gemini25p: {
    name: 'gemini25p',
    fullName: 'gemini-2.5-pro',
    openrouterFullName: 'google/gemini-2.5-pro',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 1.25, // 2.5 for >200K
    outputPrice: 10.0, // 20 for >200K
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsNativeCodeExecution: true,
      supportsNativeWebSearch: true,
      supportsNativeMCPServer: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini25p0605: {
    name: 'gemini25p',
    fullName: 'gemini-2.5-pro-preview-06-05',
    openrouterFullName: 'google/gemini-2.5-pro-preview',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 1.25,
    outputPrice: 10.0,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsNativeCodeExecution: true,
      supportsNativeWebSearch: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini25p0506: {
    name: 'gemini25p',
    fullName: 'gemini-2.5-pro-preview-05-06',
    openrouterFullName: 'google/gemini-2.5-pro-preview-05-06',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 1.25,
    outputPrice: 10.0,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsNativeCodeExecution: true,
      supportsNativeWebSearch: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini25p0325: {
    name: 'gemini25p',
    fullName: 'gemini-2.5-pro-exp-03-25',
    openrouterFullName: 'google/gemini-2.5-pro-exp-03-25:free',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 1.25,
    outputPrice: 10.0,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsNativeCodeExecution: true,
      supportsNativeWebSearch: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini2p: {
    name: 'gemini2p',
    fullName: 'gemini-2.0-pro-exp-02-05',
    openrouterFullName: 'google/gemini-2.0-pro-exp-02-05:free',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 8192,
    contextWindow: 2097152,
    inputPrice: 1.25,
    outputPrice: 5.0,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsPromptCaching: true,
      supportsNativeCodeExecution: true,
      supportsNativeWebSearch: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini25f: {
    name: 'gemini25f',
    fullName: 'gemini-2.5-flash',
    openrouterFullName: 'google/gemini-2.5-flash',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 0.3,
    outputPrice: 2.5,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsNativeCodeExecution: true,
      supportsNativeWebSearch: true,
      supportsNativeMCPServer: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini25f0520: {
    name: 'gemini25f',
    fullName: 'gemini-2.5-flash-preview-05-20',
    openrouterFullName: 'google/gemini-2.5-flash-preview-05-20:thinking',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 0.15,
    outputPrice: 3.5,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsNativeCodeExecution: true,
      supportsNativeWebSearch: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini25f0417: {
    name: 'gemini25f',
    fullName: 'gemini-2.5-flash-preview-04-17',
    openrouterFullName: 'google/gemini-2.5-flash-preview-04-17:thinking',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 0.15,
    outputPrice: 3.5,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsNativeCodeExecution: true,
      supportsNativeWebSearch: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  'gemini25f-': {
    name: 'gemini25f-',
    fullName: 'gemini-2.5-flash-lite-preview-06-17',
    openrouterFullName: 'google/gemini-2.5-flash-lite-preview-06-17',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 32768,
    contextWindow: 65536,
    inputPrice: 0.1,
    outputPrice: 0.4,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsNativeCodeExecution: false, // Lite doesn't support code execution
      supportsNativeWebSearch: false, // Lite doesn't support search grounding
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini2fT: {
    name: 'gemini2fT',
    fullName: 'gemini-2.0-flash-thinking-exp-01-21',
    openrouterFullName: 'google/gemini-2.0-flash-thinking-exp:free',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsPromptCaching: true,
      supportsNativeCodeExecution: true,
      supportsNativeWebSearch: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini2f: {
    name: 'gemini2f',
    fullName: 'gemini-2.0-flash-001',
    openrouterFullName: 'google/gemini-2.0-flash-001',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 8192,
    contextWindow: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsPromptCaching: true,
      supportsNativeCodeExecution: true,
      supportsNativeWebSearch: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini15p: {
    name: 'gemini15p',
    fullName: 'gemini-1.5-pro-latest',
    openrouterFullName: 'google/gemini-1.5-pro',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 8192,
    contextWindow: 1048576,
    inputPrice: 1.25,
    outputPrice: 5.0,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsNativeCodeExecution: true,
      supportsNativeWebSearch: false, // 1.5 models don't support search grounding
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  gemini15f: {
    name: 'gemini15f',
    fullName: 'gemini-1.5-fresh-latest',
    openrouterFullName: 'google/gemini-1.5-fresh',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 8192,
    contextWindow: 1048576,
    inputPrice: 0.075,
    outputPrice: 0.3,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsNativeCodeExecution: true,
      supportsNativeWebSearch: false, // 1.5 models don't support search grounding
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
};
