import {
  DEFAULT_MODEL_CAPABILITIES,
  ModelCapabilities,
  ModelConfig,
  ModelProvider,
  ReasoningEffort,
} from '../ModelConfig';

// Common capabilities for OpenAI reasoning models
const OPENAI_REASONING_DEFAULT_CAPABILITIES: ModelCapabilities = {
  ...DEFAULT_MODEL_CAPABILITIES,
  supportsAutoPromptCaching: true,
  cacheDiscountFactor: 0.5,
  supportsReasoning: true,
  supportsIntermDevMsgs: true,
  reasoningEffort: ReasoningEffort.HIGH,
  supportsReasoningEffort: true,
};

export const OPENAI_REASONING_MODELS: Record<string, ModelConfig> = {
  'o4-': {
    name: 'o4-',
    fullName: 'o4-mini-2025-04-16',
    openrouterFullName: 'openai/o4-mini-high',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 1.0,
    outputPrice: 4.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.25,
      supportsVision: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  o3: {
    name: 'o3',
    fullName: 'o3-2025-04-16',
    openrouterFullName: 'openai/o3',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 10.0,
    outputPrice: 40.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.25,
      supportsVision: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  'o3-': {
    name: 'o3-',
    fullName: 'o3-mini-2025-01-31',
    openrouterFullName: 'openai/o3-mini-2025-01-31',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  o1: {
    name: 'o1',
    fullName: 'o1-2024-12-17',
    openrouterFullName: 'openai/o1-2024-12-17',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 60.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: true,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  o1preview: {
    name: 'o1preview',
    fullName: 'o1-preview-2024-09-12',
    openrouterFullName: 'openai/o1-preview-2024-09-12',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 32768,
    contextWindow: 128000,
    inputPrice: 15.0,
    outputPrice: 60.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
      supportsSystemPrompt: false,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
  'o1-': {
    name: 'o1-',
    fullName: 'o1-mini-2024-09-12',
    openrouterFullName: 'openai/o1-mini-2024-09-12',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 65536,
    contextWindow: 128000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
      supportsSystemPrompt: false,
    } satisfies ModelCapabilities,
    openRouterOnly: false,
  },
};
